/**
 * Clerk Simplified Chinese UI messages from @clerk/localizations 4.20.0.
 * Kept with the lazy authentication boundary so local-only builds do not load them.
 * Source: https://github.com/clerk/javascript/tree/main/packages/localizations
 *
 * MIT License
 *
 * Copyright (c) 2022 Clerk, Inc.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */
// Missing upstream entries are completed for the account and sign-in flows.
export const clerkZhCN = {
  locale: "zh-CN",
  actionBlocked: {
    subtitle: "出于安全考虑，无法完成此请求。",
    title: "无法完成此请求",
    traceIdLabel: "参考编号",
  },
  apiKeys: {
    copySecret: {
      formButtonPrimary__copyAndClose: "复制并关闭",
      formHint: "出于安全原因，我们不会允许您稍后再次查看。",
      formTitle: '立即复制您的"{{name}}" API密钥',
    },
    revokeConfirmation: {
      confirmationText: "撤销",
      formButtonPrimary__revoke: "撤销密钥",
      formHint: "确定要删除此私密密钥吗？",
      formTitle: "撤销私密密钥“{{apiKeyName}}”？",
      inputLabel: "输入“撤销”以确认",
    },
    action__add: "添加新密钥",
    action__search: "搜索密钥",
    createdAndExpirationStatus__expiresOn:
      "创建于 {{ createdDate | shortDate('en-US') }} • 到期于 {{ expiresDate | longDate('en-US') }}",
    createdAndExpirationStatus__never: "创建于 {{ createdDate | shortDate('en-US') }} • 永不过期",
    detailsTitle__emptyRow: "未找到 API 密钥",
    formButtonPrimary__add: "创建密钥",
    formFieldCaption__expiration__expiresOn: "于 {{ date }} 到期",
    formFieldCaption__expiration__never: "此密钥永不过期",
    formFieldOption__expiration__180d: "180 天",
    formFieldOption__expiration__1d: "1 天",
    formFieldOption__expiration__1y: "1 年",
    formFieldOption__expiration__30d: "30 天",
    formFieldOption__expiration__60d: "60 天",
    formFieldOption__expiration__7d: "7 天",
    formFieldOption__expiration__90d: "90 天",
    formFieldOption__expiration__never: "永不",
    formHint: "输入名称以生成新密钥。你可以随时撤销密钥。",
    formTitle: "添加新 API 密钥",
    lastUsed__days: "{{days}} 天前",
    lastUsed__hours: "{{hours}} 小时前",
    lastUsed__minutes: "{{minutes}} 分钟前",
    lastUsed__months: "{{months}} 个月前",
    lastUsed__seconds: "{{seconds}} 秒前",
    lastUsed__years: "{{years}} 年前",
    menuAction__revoke: "撤销密钥",
    tableHeader__actions: "操作",
    tableHeader__lastUsed: "上次使用",
    tableHeader__name: "名称",
  },
  backButton: "返回",
  badge__default: "默认",
  badge__otherImpersonatorDevice: "其他模拟器设备",
  badge__primary: "主要",
  badge__requiresAction: "需要操作",
  badge__thisDevice: "此设备",
  badge__unverified: "未验证",
  badge__userDevice: "用户设备",
  badge__you: "您",
  billing: {
    checkout: {
      emailForm: {
        subtitle: "完成购买前，请先添加用于接收收据的电子邮箱地址。",
        title: "添加电子邮箱地址",
      },
      lineItems: {
        title__freeTrialEndsAt: "试用结束日期",
        title__paymentMethod: "付款方式",
        title__statementId: "账单 ID",
        title__subscriptionBegins: "订阅开始日期",
        title__totalPaid: "已支付总额",
      },
      addPromoCode: "添加优惠码",
      applyPromoCode: "应用",
      description__paymentSuccessful: "付款成功。",
      description__subscriptionSuccessful: "你的新订阅已准备就绪。",
      discount: "优惠",
      downgradeNotice: "你可以继续使用当前订阅及其功能，直至本计费周期结束，之后将切换到此订阅。",
      pastDueNotice: "你之前的订阅已逾期，尚未付款。",
      perMonth: "每月",
      promoCodePlaceholder: "输入优惠码",
      removePromoCode: "移除优惠码",
      title: "结账",
      title__paymentSuccessful: "付款成功",
      title__subscriptionSuccessful: "成功",
      title__trialSuccess: "试用已成功开始",
      totalDueAfterTrial: "试用将在 {{days}} 天后结束，届时应付总额",
      totalDuePerPeriod: "每期应付总额",
    },
    paymentMethod: {
      applePayDescription: {
        annual: "年度付款",
        monthly: "月度付款",
      },
      dev: {
        anyNumbers: "任意数字",
        cardNumber: "卡号",
        cvcZip: "CVC、ZIP",
        developmentMode: "开发模式",
        expirationDate: "到期日期",
        testCardInfo: "测试卡信息",
      },
    },
    pricingTable: {
      seatCost: {
        tooltip: {
          additionalSeatsEach: "每个额外席位收费 {{feePerBlockAmount}}/{{period}}。",
          firstSeatsIncludedInPlan: "方案包含前 {{endsAfterBlock}} 个席位。",
          freeForUpToSeats: "{{endsAfterBlock}} 个及以下席位免费。",
        },
        additionalSeats:
          "（额外费用为 {{additionalTierFeePerBlockAmount}}/{{periodAbbreviation}}）",
        freeUpToSeats: "{{endsAfterBlock}} 个及以下席位免费",
        includedSeats: "包含 {{includedSeats}} 个席位",
        perSeat: "每席位 {{feePerBlockAmount}}/{{periodAbbreviation}}",
        unlimitedSeats: "席位数量不限",
        upToSeats: "最多 {{endsAfterBlock}} 个席位",
      },
      billingCycle: "计费周期",
      included: "已包含",
    },
    subscriptionDetails: {
      beginsOn: "开始日期",
      currentBillingCycle: "当前计费周期",
      endsOn: "结束日期",
      firstPaymentAmount: "首次付款金额",
      firstPaymentOn: "首次付款日期",
      nextPaymentAmount: "下次付款金额",
      nextPaymentOn: "下次付款日期",
      pastDueAt: "逾期日期",
      renewsAt: "续订日期",
      subscribedOn: "订阅日期",
      title: "订阅",
      trialEndsOn: "试用结束日期",
      trialStartedOn: "试用开始日期",
    },
    accountCredit: "账号余额",
    addPaymentMethod__label: "添加付款方式",
    alwaysFree: "永久免费",
    annually: "每年",
    availableFeatures: "可用功能",
    billedAnnually: "按年计费",
    billedAnnuallyOnly: "仅支持按年计费",
    billedMonthly: "按月计费",
    billedMonthlyOnly: "仅支持按月计费",
    cancelFreeTrial: "取消免费试用",
    cancelFreeTrialAccessUntil:
      "你的试用将持续至 {{ date | longDate('en-US') }}。此后，你将无法使用试用功能，且不会被收费。",
    cancelFreeTrialTitle: "取消 {{plan}} 方案的免费试用？",
    cancelSubscription: "取消订阅",
    cancelSubscriptionAccessUntil:
      "你可以继续使用“{{plan}}”的功能，直至 {{ date | longDate('en-US') }}。此后，你将无法使用这些功能。",
    cancelSubscriptionNoCharge: "此订阅不会向你收费。",
    cancelSubscriptionPastDue:
      "你的订阅将立即结束，所有方案功能将不可用。下次订阅时，你需要支付逾期欠款。",
    cancelSubscriptionTitle: "取消 {{plan}} 订阅？",
    cannotSubscribeMonthly: "此方案无法按月订阅。如需订阅，请选择按年付款。",
    cannotSubscribeUnrecoverable: "无法订阅此方案。你现有的订阅费用高于此方案。",
    credit: "抵扣额",
    creditRemainder: "当前订阅剩余时段的抵扣额。",
    defaultFreePlanActive: "你目前使用免费方案",
    discountAmount: "减免 {{amount}}",
    discountCyclesRemaining: "剩余 {{cycles}} 个{{period}}",
    discountDuration: "前 {{cycles}} 个{{period}}减免 {{amount}}",
    free: "免费",
    getStarted: "开始使用",
    highlightedPlanBadge: "热门",
    keepFreeTrial: "保留免费试用",
    keepSubscription: "保留订阅",
    manage: "管理",
    manageSubscription: "管理订阅",
    month: "月",
    monthAbbreviation: "月",
    monthPerUnit: "每 {{unitName}} 每月",
    monthly: "每月",
    months: "个月",
    pastDue: "已逾期",
    pay: "支付 {{amount}}",
    payerCreditRemainder: "从账号余额中抵扣。",
    paymentMethods__label: "付款方式",
    proratedDiscount: "按比例计算的优惠",
    prorationCredit: "按比例计算的抵扣额",
    reSubscribe: "重新订阅",
    seatBreakdownIncludedPlural:
      "{{chargeable}} 个席位，每席位每月 {{rate}}（共 {{totalSeats}} 个，已包含 {{included}} 个）",
    seatBreakdownIncludedSingular:
      "1 个席位，每月 {{rate}}（共 {{totalSeats}} 个，已包含 {{included}} 个）",
    seatBreakdownPlural: "{{chargeable}} 个席位，每席位每月 {{rate}}",
    seatBreakdownSingular: "1 个席位，每月 {{rate}}",
    seats: "席位",
    seatsWithLimit: "席位（最多 {{limit}} 个）",
    seeAllFeatures: "查看全部功能",
    startFreeTrial: "开始免费试用",
    startFreeTrial__days: "开始 {{days}} 天免费试用",
    subscribe: "订阅",
    subtotal: "小计",
    subtotalRenewal: "每期小计",
    switchPlan: "切换到此方案",
    switchToAnnual: "切换为按年付费",
    switchToAnnualWithAnnualPrice: "切换为按年付费，每年 {{price}}",
    switchToMonthly: "切换为按月付费",
    switchToMonthlyWithPrice: "切换为按月付费，每月 {{price}}",
    totalDue: "应付总额",
    totalDuePerPeriod: "每期总额",
    totalDueToday: "今日应付总额",
    viewFeatures: "查看功能",
    viewPayment: "查看付款",
    year: "年",
    yearAbbreviation: "年",
    yearPerUnit: "每 {{unitName}} 每年",
    years: "年",
  },
  configureDirectorySync: {
    attributeMappingStep: {
      columns: {
        clerkAttribute: "用户属性",
        directoryAttribute: "目录属性",
      },
      subtitle: "标准目录属性已预先配置。此处未列出的属性将被忽略。",
      title: "检查属性",
    },
    configureStep: {
      error__ssoRequired: {
        subtitle: "目录同步需要 SSO 连接。请先配置并验证 SSO 连接，再返回此处设置用户预配。",
        title: "尚未配置单点登录",
      },
      instructions: {
        custom: {
          step1: "在你的身份提供商中创建 SCIM 2.0 用户预配集成。",
          step2: "将 SCIM 端点 URL 粘贴为集成的基础 URL。",
          step3: "配置集成，使用下方的 Bearer 令牌进行身份验证。",
          step4: "启用用户创建、更新和停用事件的自动预配。",
        },
        entra: {
          step1: "在 Microsoft Entra 管理中心打开“企业应用程序”，选择 SSO 连接使用的应用程序。",
          step2:
            "在“连接”下，将 SCIM 端点 URL 粘贴到“租户 URL”，将 Bearer 令牌粘贴到“密钥令牌”，然后选择“测试连接”。",
          step3: "选择“配置”，将配置模式设为“自动”。",
          step4: "分配需要预配的用户和组，然后将预配设为“开启”。",
        },
        okta: {
          step1: "在 Okta 管理控制台中，打开 SSO 连接使用的应用程序。",
          step2: "打开“配置”选项卡，选择“集成”设置。",
          step3: "粘贴下方的 SCIM 端点 URL 和 Bearer 令牌。",
          step4: "在预配操作中，启用“新用户”“个人资料更新”和“组”的推送。",
        },
        actionLabel__toggle: "查看说明",
      },
      warning__googleUnsupported: {
        subtitle: "请联系支持团队设置 Google Workspace 集成。",
        title: "Google Workspace 连接无法自助配置",
      },
      actionLabel__generateToken: "生成新令牌",
      actionLabel__retry: "重试",
      domainsLabel: "域名：",
      formFieldInputPlaceholder__token: "生成新令牌以查看",
      formFieldLabel__endpointUrl: "SCIM 端点 URL",
      formFieldLabel__token: "Bearer 令牌",
      notice__tokenShownOnce: "此令牌仅显示一次。如果丢失，请生成新令牌。",
      subtitle: "将这些凭据添加到你的身份提供商，以配置目录同步",
      title: "配置",
      warning__ssoInactive:
        "SSO 连接已配置，但尚未启用。现在可以预配成员，但成员只有在 SSO 启用后才能登录。",
    },
    navbar: {
      title: "配置目录同步",
    },
    providers: {
      custom: "自定义 SCIM 提供商",
      entra: "Microsoft Entra ID",
      google: "Google Workspace",
      okta: "Okta Workforce",
    },
    stepper: {
      attributes: "属性",
      configure: "配置",
      test: "测试",
    },
    testStep: {
      actionLabel__complete: "完成",
      badge__active: "已启用",
      badge__deprovisioned: "已解除预配",
      description: "身份提供商预配的用户会显示在这里，按最近活动优先排序。",
      empty__waitingForFirstUser: "正在等待首个完成预配的用户…",
      error__loadUsers: "无法加载已预配的用户",
      note: "仅处理电子邮箱地址属于已配置域名的用户。",
      noteLabel: "注意：",
      subtitle: "从 {{provider}} 分配或推送一个测试用户，以验证预配。",
      title: "测试预配",
    },
  },
  configureSSO: {
    activate: {
      activateButton: "启用 SSO",
      activeSubtitle: "使用 {{domain}} 登录的所有人都必须通过你的身份提供商登录。",
      activeTitle: "SSO 连接已启用",
      doneButton: "完成",
      skipButton: "暂时跳过",
      subtitle:
        "SSO 连接已准备就绪。启用后，使用 {{domain}} 登录的所有人都必须通过你的身份提供商登录。",
      title: "SSO 连接已配置",
    },
    changeProviderDialog: {
      cancelButton: "取消",
      confirmButton: "更换提供商",
      subtitle: "切换到 {{provider}} 将移除 {{currentProvider}} 连接“{{name}}”，并需要重新设置。",
      title: "将提供商更换为 {{provider}}",
    },
    configureStep: {
      activeConnectionWarning: {
        dismiss: "关闭",
        title: "此连接已启用。保存的更改会立即生效，可能影响现有成员登录。",
      },
      attributeMappingTable: {
        badges: {
          optional: "可选",
          required: "必填",
        },
      },
      oidcCustom: {
        credentialsStep: {
          clientId: {
            label: "客户端 ID",
            placeholder: "在此粘贴客户端 ID…",
          },
          clientSecret: {
            label: "客户端密钥",
            placeholder: "在此粘贴客户端密钥…",
          },
          headerSubtitle: "添加应用程序凭据",
          paragraph: "在身份提供商的 OIDC 应用程序中获取这些值。",
        },
        endpointsStep: {
          discoveryUrl: {
            description: "在身份提供商的 OIDC 应用程序中获取发现端点，并粘贴到下方。",
            label: "发现端点",
            placeholder: "在此粘贴 URL…",
          },
          manual: {
            authUrl: {
              label: "授权 URL",
              placeholder: "在此粘贴 URL…",
            },
            tokenUrl: {
              label: "令牌 URL",
              placeholder: "在此粘贴 URL…",
            },
            userInfoUrl: {
              label: "用户信息 URL",
              placeholder: "在此粘贴 URL…",
            },
            description: "在身份提供商的 OIDC 应用程序中获取这些值。",
          },
          modes: {
            ariaLabel: "OIDC 端点配置方式",
            discoveryUrl: "通过发现端点添加",
            manual: "手动配置",
          },
          headerSubtitle: "添加身份提供商的端点",
        },
        redirectUriStep: {
          claims: {
            table: {
              columns: {
                attribute: "Clerk 属性",
                claim: "ID 令牌声明",
              },
              rows: {
                email: {
                  attribute: "主要电子邮箱",
                },
                firstName: {
                  attribute: "名",
                },
                lastName: {
                  attribute: "姓",
                },
                subject: {
                  attribute: "外部用户 ID",
                },
              },
            },
            description: "确保 ID 令牌包含以下声明：",
          },
          redirectUri: {
            label: "授权重定向 URI",
          },
          headerSubtitle: "在身份提供商的控制台中创建新的 OIDC 应用程序",
          paragraph:
            "在身份提供商的控制台中，创建支持授权码授权类型的新 OIDC 应用程序，并使用以下重定向 URI：",
        },
        mainHeaderTitle: "配置身份提供商",
      },
      samlCustom: {
        assignUsersStep: {
          headerSubtitle: "向 SAML 应用程序分配用户或组",
          paragraph: "用户或组必须先分配到应用程序，才能通过 SSO 登录。",
        },
        attributeMappingStep: {
          attributeMappingTable: {
            columns: {
              attributeName: "属性名称",
              userAttribute: "用户属性",
            },
            rows: {
              email: {
                attributeName: "主要电子邮箱",
                userAttribute: "mail",
              },
              firstName: {
                attributeName: "名",
                userAttribute: "firstName",
              },
              lastName: {
                attributeName: "姓",
                userAttribute: "lastName",
              },
            },
          },
          headerSubtitle: "将身份提供商中的用户属性映射到应用程序。",
          paragraph: "SAML 响应必须包含以下属性：",
        },
        createAppStep: {
          createAppInstructions: {
            paragraph:
              "在身份提供商的控制台中创建新的 SAML 2.0 应用程序，并使用以下服务提供商信息：",
          },
          serviceProviderFields: {
            acsUrl: {
              label: "断言消费者服务（ACS）URL",
            },
            spEntityId: {
              label: "实体 ID",
            },
          },
          headerSubtitle: "在身份提供商的控制台中创建新的 SAML 应用程序",
        },
        identityProviderMetadataStep: {
          manual: {
            issuer: {
              label: "颁发者",
              placeholder: "在此粘贴 URL…",
            },
            signOnUrl: {
              label: "登录 URL",
              placeholder: "在此粘贴 URL…",
            },
            signingCertificate: {
              fileUploaded: "文件已上传",
              label: "签名证书",
              removeFile: "移除文件",
              replaceFile: "替换文件",
              uploadFile: "上传文件",
            },
            description: "在身份提供商的 SAML 应用程序中获取这些值。",
          },
          metadataUrl: {
            description: "在身份提供商的 SAML 应用程序中获取元数据 URL，并粘贴到下方。",
            label: "元数据 URL",
            placeholder: "在此粘贴 URL…",
          },
          modes: {
            ariaLabel: "配置 ",
            manual: "手动配置",
            metadataUrl: "通过元数据添加",
          },
          headerSubtitle: "配置身份提供商元数据",
        },
        mainHeaderTitle: "配置身份提供商",
      },
      samlGoogle: {
        attributeMappingStep: {
          attributeMappingTable: {
            columns: {
              appAttribute: "应用属性",
              googleAttribute: "Google 属性",
            },
            rows: {
              email: {
                appAttribute: "email",
                googleAttribute: "主要电子邮箱",
              },
              firstName: {
                appAttribute: "firstName",
                googleAttribute: "名",
              },
              lastName: {
                appAttribute: "lastName",
                googleAttribute: "姓",
              },
            },
          },
          headerSubtitle: "将 Google Workspace 中的用户属性映射到应用程序",
          paragraph: "SAML 响应需要返回用户的电子邮箱、名和姓。",
          step1: "在 <bold>Google 管理控制台</bold>中，找到 <bold>属性</bold>部分。",
          step2: "为每个属性选择 <bold>添加映射</bold>，并输入以下 Google 属性和应用属性：",
        },
        configureUserAccess: {
          assignUsersInstructions: {
            paragraph1: "在 Google 中完成配置后，你将被重定向到应用概览页面。",
            paragraph2:
              "Google 最多可能需要 24 小时才能完成这些更改的传播。更改生效前，此连接将保持未启用状态。",
            step1: "打开 <bold>用户访问权限</bold>部分。",
            step2: "选择 <bold>对所有人开启</bold>。",
            step3: "选择 <bold>保存</bold>。",
          },
          headerSubtitle: "启用 Google Workspace SAML 应用程序",
        },
        createAppStep: {
          createAppInstructions: {
            step1: "在侧边导航栏的 <bold>应用</bold>下，选择 <bold>Web 和移动应用</bold>。",
            step2: "选择 <bold>添加应用</bold>，然后选择 <bold>添加自定义 SAML 应用</bold>。",
            step3: "输入 <bold>应用名称</bold>。",
            step4: "选择 <bold>继续</bold>。",
            title: "在 Google Workspace 中创建新的 SAML 应用程序：",
          },
          headerSubtitle: "在 Google Workspace 中创建新的 SAML 应用程序",
        },
        identityProviderMetadataStep: {
          manual: {
            issuer: {
              label: "实体 ID",
              placeholder: "在此粘贴 URL…",
            },
            signOnUrl: {
              label: "SSO URL",
              placeholder: "在此粘贴 URL…",
            },
            signingCertificate: {
              fileUploaded: "文件已上传",
              label: "签名证书",
              removeFile: "移除文件",
              replaceFile: "替换文件",
              uploadFile: "上传文件",
            },
            description: "在 Google Workspace 应用中获取这些值。",
          },
          metadataFile: {
            description: "在 Google Workspace 应用中下载 IdP 元数据，并上传到下方。",
            fileUploaded: "文件已上传",
            label: "IdP 元数据",
            removeFile: "移除文件",
            replaceFile: "替换文件",
            uploadFile: "上传文件",
          },
          modes: {
            ariaLabel: "配置",
            manual: "手动配置",
            metadataFile: "通过元数据添加",
          },
          headerSubtitle: "添加 Google Workspace 应用程序元数据",
        },
        serviceProviderStep: {
          nameIdInstructions: {
            step1:
              "在 <bold>名称 ID</bold>部分，打开 <bold>名称 ID</bold>格式下拉菜单，选择 <bold>电子邮箱</bold>。",
            step2: "选择 <bold>继续</bold>",
          },
          serviceProviderFields: {
            acsUrl: {
              label: "ACS URL",
            },
            spEntityId: {
              label: "实体 ID",
            },
          },
          headerSubtitle: "配置服务提供商",
          paragraph:
            "要配置服务提供商，你必须在 Google Workspace SAML 应用程序中添加以下两个字段：",
          title: "配置服务提供商",
        },
        mainHeaderTitle: "配置 Google Workspace",
      },
      samlMicrosoft: {
        attributeMappingStep: {
          attributeMappingTable: {
            columns: {
              attribute: "属性",
              claimName: "声明名称",
              value: "值",
            },
            rows: {
              email: {
                attribute: "电子邮箱地址",
                claimName: "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress",
                value: "user.mail",
              },
              firstName: {
                attribute: "名",
                claimName: "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/givenname",
                value: "user.givenname",
              },
              lastName: {
                attribute: "姓",
                claimName: "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/surname",
                value: "user.surname",
              },
            },
            copyClaimName: "复制声明名称",
            copyClaimNameCopied: "已复制",
          },
          headerSubtitle: "设置 Microsoft Entra 在 SAML 响应中包含的属性",
          step1: "在 <bold>基于 SAML 的登录</bold>页面中，找到 <bold>属性和声明</bold>部分。",
          step2: "选择 <bold>编辑</bold>。",
          title: "SAML 响应必须包含以下属性：",
        },
        createAppStep: {
          assignUsersInstructions: {
            step1: "在 <bold>开始使用</bold>部分，选择 <bold>分配用户和组</bold>。",
            step2: "选择 <bold>添加用户/组</bold>。你将被重定向到 <bold>添加分配页面</bold>。",
            step3: "选择 <bold>未选择任何项链接</bold>。",
            step4: "选择页面底部的 <bold>选择</bold>，你将被重定向到 <bold>添加分配</bold>页面。",
            step5: "选择 <bold>分配</bold>",
            title: "在 Microsoft 中分配用户或组",
          },
          createAppInstructions: {
            step4: {
              subSteps: {
                appName: "填写应用程序名称。",
                create: "选择 <bold>创建</bold>。",
                nonGallery: "选择 <bold>集成库中找不到的任何其他应用程序（非库）</bold>。",
              },
              label: "在打开的弹窗中：",
            },
            step1: "登录 Microsoft Azure 门户，前往 <bold>企业应用程序</bold>。",
            step2:
              "点击 <bold>新建应用程序</bold>。你将被重定向到 <bold>浏览 Microsoft Entra 库</bold>页面。",
            step3: "选择 <bold>创建自己的应用程序</bold>。",
            title: "创建新的企业应用程序",
          },
          headerSubtitle: "在 Azure 门户中创建新的企业应用程序",
        },
        identityProviderMetadataStep: {
          manual: {
            issuer: {
              label: "颁发者",
              placeholder: "在此粘贴 URL…",
            },
            signOnUrl: {
              label: "登录 URL",
              placeholder: "在此粘贴 URL…",
            },
            signingCertificate: {
              fileUploaded: "文件已上传",
              label: "签名证书",
              removeFile: "移除文件",
              replaceFile: "替换文件",
              uploadFile: "上传文件",
            },
            description:
              "在 <bold>基于 SAML 的登录</bold>页面中，找到 <bold>SAML 证书</bold>部分。获取这些值并添加到下方。",
          },
          metadataUrl: {
            description:
              "在 <bold>基于 SAML 的登录</bold>页面中，找到 <bold>SAML 证书</bold>部分，复制 <bold>应用联合元数据 URL</bold>并粘贴到下方。",
            label: "元数据 URL",
            placeholder: "在此粘贴 URL…",
          },
          modes: {
            ariaLabel: "配置 ",
            manual: "手动配置",
            metadataUrl: "通过元数据添加",
          },
          headerSubtitle: "添加 Microsoft Entra 应用程序元数据",
        },
        serviceProviderStep: {
          serviceProviderFields: {
            acsUrl: {
              label: "回复 URL（断言消费者服务 URL）",
            },
            spEntityId: {
              label: "标识符（实体 ID）",
            },
          },
          headerSubtitle: "将服务提供商配置添加到 Microsoft Entra",
          step1: "在侧边导航栏中，打开 <bold>管理</bold>下拉菜单，选择“单点登录”。",
          step2: "在 <bold>选择单点登录方法</bold>部分中，选择 <bold>SAML</bold>。",
          step3: "找到 <bold>基本 SAML 配置</bold>部分。",
          step4: "选择 <bold>编辑</bold>，将打开 <bold>基本 SAML 配置</bold>面板。",
          step5:
            "将以下值复制到 <bold>标识符（实体 ID）</bold>和 <bold>回复 URL（ACS URL）</bold>：",
          step6: "选择面板顶部的 <bold>保存</bold>，然后关闭面板。",
          title: "添加服务提供商信息",
        },
        mainHeaderTitle: "配置 Microsoft Entra",
      },
      samlOkta: {
        assignUsersStep: {
          assignUsersInstructions: {
            paragraph: "先向 Okta 应用程序分配用户或组，才能通过 SSO 登录",
            step1: "在 Okta 控制台中，选择 <bold>分配</bold>选项卡。",
            step2:
              "打开 <bold>分配</bold>下拉菜单，选择 <bold>分配给用户</bold>或 <bold>分配给组</bold>。",
            step3: "搜索要分配的用户或组。",
            step4: "点击用户或组旁边的 <bold>分配</bold>。",
            step5: "点击 <bold>完成</bold>。",
          },
          headerSubtitle: "向 Okta 应用程序分配用户",
        },
        attributeMappingStep: {
          attributeMappingTable: {
            columns: {
              expression: "表达式",
              name: "属性名称",
            },
            rows: {
              email: {
                expression: "user.profile.email",
                name: "mail",
              },
              firstName: {
                expression: "user.profile.firstName",
                name: "firstName",
              },
              lastName: {
                expression: "user.profile.lastName",
                name: "lastName",
              },
            },
          },
          headerSubtitle: "设置 Okta 在 SAML 响应中包含的属性",
          paragraph: "SAML 响应必须包含以下属性：",
          step1: "在 Okta 控制台中，找到 <bold>属性语句</bold>部分。",
          step2: "为每个属性选择 <bold>添加表达式</bold>，并输入以下名称和表达式对：",
        },
        createAppStep: {
          completeSamlIntegrationInstructions: {
            step1: "在 <bold>反馈</bold>中，选择 <bold>这是我们创建的内部应用</bold>。",
            step2: "点击 <bold>完成</bold>以完成集成。",
            title: "完成 SAML 集成",
          },
          createAppInstructions: {
            step1: "登录 Okta，前往 <bold>管理 → 应用程序</bold>。",
            step2: "点击 <bold>创建应用集成</bold>，选择 <bold>SAML 2.0</bold>。",
            step3: "填写常规设置。应用名称为必填项。",
            step4: "点击 <bold>下一步</bold>以完成应用程序创建。",
            title: "在 Okta 中创建新的 SAML 应用程序",
          },
          serviceProviderInstructions: {
            serviceProviderFields: {
              acsUrl: {
                label: "单点登录 URL",
              },
              spEntityId: {
                label: "受众 URI（SP 实体 ID）",
              },
            },
            paragraph1: "完成 <bold>常规设置</bold>后，你将看到 <bold>配置 SAML</bold>页面。",
            paragraph2: "在 Okta 应用程序中添加这两个字段，以配置服务提供商。",
            title: "配置服务提供商",
          },
          headerSubtitle: "在 Okta 控制台中创建并配置 SAML 应用程序",
        },
        identityProviderMetadataStep: {
          manual: {
            issuer: {
              label: "颁发者",
              placeholder: "在此粘贴 URL…",
            },
            signOnUrl: {
              label: "登录 URL",
              placeholder: "在此粘贴 URL…",
            },
            signingCertificate: {
              fileUploaded: "文件已上传",
              label: "签名证书",
              removeFile: "移除文件",
              replaceFile: "替换文件",
              uploadFile: "上传文件",
            },
            description: "在 Okta SAML 应用程序中，前往 <bold>登录</bold>选项卡并获取这些值。",
          },
          metadataUrl: {
            description:
              "在 Okta SAML 应用程序中，前往 <bold>登录</bold>选项卡，获取元数据 URL 并粘贴到下方。",
            label: "元数据 URL",
            placeholder: "在此粘贴 URL…",
          },
          modes: {
            ariaLabel: "配置",
            manual: "手动配置",
            metadataUrl: "通过元数据添加",
          },
          headerSubtitle: "添加 Okta 应用程序元数据",
        },
        mainHeaderTitle: "配置 Okta Workforce",
      },
      unsupportedProvider: {
        description: "此版本的 Clerk 不支持该身份提供商。请更新到最新版本，以完成设置。",
        title: "不受支持的提供商",
      },
    },
    connectionScopeBanner: {
      subtitle__adding: "此组织已有 {{count}} 个 SSO 连接。",
      subtitle__editing: "此组织有 {{count}} 个 SSO 连接。此处的更改仅应用于当前连接。",
      title__adding: "添加新的 SSO 连接",
      title__editing: "正在编辑“{{name}}”",
    },
    missingManageEnterpriseConnectionsPermission: {
      subtitle: "请联系您的组织管理员以升级您的权限。",
      title: "您无权管理单点登录 (SSO)",
    },
    navbar: {
      title: "配置单点登录 (SSO)",
    },
    organizationDomainsStep: {
      domainCard: {
        badge__unverified: "未验证",
        badge__verified: "已验证",
        txtRecord: {
          hostLabel: "主机 / 名称",
          instructions: "将此 TXT 记录添加到您的 DNS 提供商。记录生效后，我们将自动进行验证。",
          typeLabel: "类型",
          valueLabel: "值",
        },
        verifiedAtLabel: "验证于 {{ date | shortDate('zh-CN') }}",
        badge__claimed: "已被其他连接使用",
        badge__expired: "已过期",
        checkboxLabel: "将 {{domain}} 用于此连接",
        expiredAtLabel:
          "域名验证已于 {{ date | shortDate('en-US') }} 过期。请重新验证以生成新的 DNS 记录。",
        expiredLabel: "域名验证已过期。请重新验证以生成新的 DNS 记录。",
        removeButtonTooltip__lastVerifiedDomain: "设置 SSO 至少需要一个已验证的域名。",
        removeButtonTooltip__lastVerifiedDomainActive: "保持 SSO 启用至少需要一个已验证的域名。",
        verifyAgainButton: "重新验证",
      },
      domainSuggestion: {
        formButtonPrimary__add: "添加 {{domain}}",
        messageLabel: "您的邮箱使用了 {{domain}}。是否要添加它？",
      },
      formButtonPrimary__add: "添加",
      formFieldInputPlaceholder__domain: "添加域名",
      formFieldLabel__domain: "域名",
      removeDomainDialog: {
        cancelButton: "取消",
        removeButton: "移除域名",
        subtitle__active: "你即将从此企业连接中移除 {{domain}}。用户将无法再使用 {{domain}} 登录。",
        subtitle__inactive: "你即将从此企业连接中移除 {{domain}}。",
        title: "正在移除域名",
      },
      subtitle: "添加并验证贵组织用于登录的域名的所有权。",
      title: "添加 SSO 域名",
    },
    resetConnectionDialog: {
      cancelButton: "取消",
      confirmationFieldLabel: "在下方输入“{{name}}”以继续",
      confirmationFieldPlaceholder: "{{name}}",
      resetButton: "重置连接",
      subtitle: "确定要重置连接“{{name}}”吗？此操作无法撤销，你需要重新配置所有步骤",
      title: "重置连接",
    },
    selectProviderStep: {
      oidc: {
        groupLabel: "OpenID Connect（OIDC）",
        oidcProvider: "OIDC 提供商",
      },
      saml: {
        customSaml: "自定义 SAML 提供商",
        groupLabel: "SAML",
        okta: "Okta Workforce",
        google: "Google Workspace",
        microsoft: "Microsoft Entra（原 AD）",
      },
      subtitle: "选择您要为其设置 SSO 的提供商。",
      title: "选择提供商",
      warning: "选择提供商后,在配置完成之前无法再次更改",
    },
    testConfigurationStep: {
      testResults: {
        empty: {
          subtitle: "选择 <bold>打开测试 URL</bold>，运行首次测试",
          title: "暂无测试结果",
        },
        actionLabel__refresh: "刷新日志",
        polling: "正在等待测试完成…",
        status__failed: "失败",
        status__pending: "等待中",
        status__success: "成功",
        title: "测试结果",
      },
      testRunDetails: {
        howToFix: {
          oauth_access_denied: {
            description:
              "用户在 OAuth 提供商的授权页面上点击“取消”或“拒绝”，或者提供商拒绝授权请求时，会出现此错误。请确认 OAuth 应用程序凭据（客户端 ID 和客户端密钥）配置正确。",
          },
          oauth_fetch_user_error: {
            intro: "请按照以下步骤修复此错误：",
            step1: "确认连接设置中的 OAuth 权限范围包含读取用户个人资料所需的权限。",
            step2: "确保用户信息端点 URL 配置正确。",
          },
          oauth_token_exchange_error: {
            description:
              "确认 OAuth 应用程序的客户端 ID 和客户端密钥配置正确，并与 OAuth 提供商控制台中的凭据一致。",
          },
          saml_email_address_domain_mismatch: {
            description:
              "确认用户登录时使用的电子邮箱地址属于此连接允许的域名。如需添加其他域名，请更新连接设置中的允许域名。",
          },
          saml_response_relaystate_missing: {
            description: "确认身份提供商正确返回了原始请求中发送的 RelayState 参数。",
          },
          saml_user_attribute_missing: {
            intro: "请按照以下步骤修复此错误：",
            step1: "打开身份提供商的配置控制台。",
            step2: "前往应用程序的 SAML 设置或属性映射配置。",
            step3: "确保“mail”属性已正确映射到用户的电子邮箱地址字段。",
          },
          actionLabel__viewDocumentation: "查看文档",
          sectionTitle: "修复方法",
        },
        parsedUserInfo: {
          email: "电子邮箱",
          firstName: "名",
          sectionTitle: "解析后的用户信息",
        },
        runDetails: {
          actionLabel__copied: "已复制",
          actionLabel__copy: "复制消息",
          errorCode: "错误代码",
          fullMessage: "完整消息",
          sectionTitle: "运行详情",
          status: "状态",
          timestamp: "时间戳",
        },
        title: "测试运行",
      },
      testUrl: {
        actionLabel__open: "打开测试 URL",
      },
      error__noSuccessfulTestRun: "至少需要成功测试一次才能继续。请生成测试 URL 并完成登录流程。",
      subtitle: "通过测试 URL 登录，以验证 SSO 连接是否配置正确",
      title: "测试 SSO 连接",
    },
  },
  createOrganization: {
    formButtonSubmit: "创建组织",
    invitePage: {
      formButtonReset: "跳过",
    },
    title: "创建组织",
  },
  dates: {
    lastDay: "昨天{{ date | timeString('zh-CN') }}",
    next6Days: "{{ date | weekday('zh-CN','long') }} {{ date | timeString('zh-CN') }}",
    nextDay: "明天{{ date | timeString('zh-CN') }}",
    numeric: "{{ date | numeric('zh-CN') }}",
    previous6Days: "上周{{ date | weekday('zh-CN','long') }} {{ date | timeString('zh-CN') }}",
    sameDay: "今天{{ date | timeString('zh-CN') }}",
  },
  dividerText: "或者",
  footerActionLink__useAnotherMethod: "使用另一种方法",
  footerPageLink__help: "帮助",
  footerPageLink__privacy: "隐私",
  footerPageLink__terms: "条款",
  formButtonPrimary: "继续",
  formButtonPrimary__verify: "验证",
  formFieldAction__forgotPassword: "忘记密码？",
  formFieldAction__hidePassword: "隐藏密码",
  formFieldAction__showPassword: "显示密码",
  formFieldError__matchingPasswords: "密码匹配。",
  formFieldError__notMatchingPasswords: "密码不匹配。",
  formFieldError__verificationLinkExpired: "验证链接已过期。请申请新的链接。",
  formFieldHintText__optional: "选填",
  formFieldHintText__slug: "Slug 是一个人类可读的 ID，它必须是唯一的。它通常用于 URL 中。",
  formFieldInputPlaceholder__confirmDeletionUserAccount: "删除账户",
  formFieldInputPlaceholder__emailAddress: "请输入您的电子邮件地址",
  formFieldInputPlaceholder__emailAddresses: "输入或粘贴一个或多个电子邮件地址，用空格或逗号分隔",
  formFieldInputPlaceholder__organizationSlug: "我的组织",
  formFieldLabel__apiKey: "API密钥",
  formFieldLabel__apiKeyDescription: "描述",
  formFieldLabel__apiKeyExpiration: "过期时间",
  formFieldLabel__apiKeyName: "密钥名称",
  formFieldLabel__automaticInvitations: "为此域名启用自动邀请",
  formFieldLabel__backupCode: "备用代码",
  formFieldLabel__confirmDeletion: "确认",
  formFieldLabel__confirmPassword: "确认密码",
  formFieldLabel__currentPassword: "当前密码",
  formFieldLabel__emailAddress: "电子邮件地址",
  formFieldLabel__emailAddress_username: "电子邮件地址或用户名",
  formFieldLabel__emailAddresses: "电子邮件地址",
  formFieldLabel__firstName: "名字",
  formFieldLabel__lastName: "姓氏",
  formFieldLabel__newPassword: "新密码",
  formFieldLabel__organizationDomain: "域名",
  formFieldLabel__organizationDomainDeletePending: "删除待处理的邀请和建议",
  formFieldLabel__organizationDomainEmailAddress: "验证邮箱地址",
  formFieldLabel__organizationDomainEmailAddressDescription:
    "输入此域名下的一个邮箱地址以接收验证码并验证此域名。",
  formFieldLabel__organizationName: "组织名称",
  formFieldLabel__organizationSlug: "URL 简称",
  formFieldLabel__password: "密码",
  formFieldLabel__phoneNumber: "电话号码",
  formFieldLabel__role: "角色",
  formFieldLabel__signOutOfOtherSessions: "登出所有其他设备",
  formFieldLabel__username: "用户名",
  impersonationFab: {
    action__signOut: "退出登录",
    title: "以 {{identifier}} 登录",
  },
  lastAuthenticationStrategy: "上次使用",
  membershipRole__admin: "管理员",
  membershipRole__basicMember: "成员",
  membershipRole__guestMember: "访客",
  oauthConsent: {
    redirectUriModal: {
      subtitle: "请确认你信任 {{applicationName}}，且此 URL 属于 {{applicationName}}。",
      title: "重定向 URL",
    },
    scopeList: {
      privateMetadata: "{{applicationName}} 设置的私有元数据，其中可能包含敏感信息",
      title: "这将允许 {{applicationName}} 访问：",
    },
    action__allow: "允许",
    action__deny: "拒绝",
    offlineAccessNotice: " 你将保持登录状态，直到主动退出或撤销访问权限。",
    redirectNotice: "如果你允许访问，此应用会将你重定向到 {{domainAction}}。",
    subtitle: "希望代表 {{identifier}} 访问 {{applicationName}}",
    viewFullUrl: "查看完整 URL",
    warning:
      "请确认你信任 {{applicationName}}（{{domainAction}}）。你可能会与此网站或应用共享敏感数据。",
  },
  oauthDeviceVerification: {
    confirmation: {
      action__approve: "批准",
      action__deny: "拒绝",
      scopeListTitle: "这将允许 {{applicationName}} 访问：",
      subtitle: "确认 {{identifier}} 的此请求",
      title: "允许 {{applicationName}} 访问你的账号？",
      warning: "仅当你在另一台设备上发起此请求时，才批准它。",
    },
    error: {
      expiredSubtitle: "请在你的设备上重新开始。",
      expiredTitle: "此验证码已过期",
      genericSubtitle: "请检查网络连接后重试。",
      genericTitle: "无法验证此验证码",
      invalidCode: "请输入有效的 8 字符验证码。",
      rateLimitedSubtitle: "请稍后再尝试其他验证码。",
      rateLimitedTitle: "尝试次数过多",
      unknownCode: "未找到此验证码。请检查后重试。",
    },
    start: {
      action__continue: "继续",
      subtitle: "输入你要授权的设备或应用上显示的验证码。",
      title: "验证设备",
      userCodeLabel: "设备验证码",
    },
    status: {
      alreadyApprovedSubtitle: "返回你的设备以继续。",
      alreadyApprovedTitle: "你已批准此请求",
      alreadyDecidedSubtitle: "此请求已在其他位置处理。请返回你的设备。",
      alreadyDecidedTitle: "此请求已完成",
      alreadyDeniedSubtitle: "如需重试，请在你的设备上重新开始。",
      alreadyDeniedTitle: "此请求已被拒绝",
      approvedSubtitle: "你已批准此请求。请返回你的设备以继续。",
      approvedTitle: "设备已获批准",
      consumedSubtitle: "你的设备已获授权，可以关闭此窗口。",
      consumedTitle: "此验证码已使用",
      deniedSubtitle: "你已拒绝此请求。请返回你的设备。",
      deniedTitle: "访问被拒绝",
    },
    action__tryAnotherCode: "输入其他验证码",
  },
  organizationList: {
    action__createOrganization: "创建组织",
    action__invitationAccept: "加入",
    action__suggestionsAccept: "请求加入",
    createOrganization: "创建组织",
    invitationAcceptedLabel: "已加入",
    subtitle: "以继续使用 {{applicationName}}",
    suggestionsAcceptedLabel: "等待批准",
    title: "选择一个账户",
    titleWithoutPersonal: "选择一个组织",
  },
  organizationProfile: {
    apiKeysPage: {
      title: "API 密钥",
    },
    badge__automaticInvitation: "自动邀请",
    badge__automaticSuggestion: "自动建议",
    badge__manualInvitation: "无自动注册",
    badge__unverified: "未验证",
    billingPage: {
      accountCreditsSection: {
        title: "账号余额",
        viewHistory: "查看余额记录",
      },
      creditHistoryPage: {
        tableHeader__amount: "金额",
        tableHeader__date: "日期",
        title: "账号余额记录",
      },
      paymentHistorySection: {
        empty: "暂无付款记录",
        notFound: "未找到付款尝试",
        tableHeader__amount: "金额",
        tableHeader__date: "日期",
        tableHeader__status: "状态",
      },
      paymentMethodsSection: {
        removeMethod: {
          messageLine1: "{{identifier}} 将从此账号中移除。",
          messageLine2: "你将无法再使用此付款方式，依赖它的定期订阅也将停止正常续费。",
          successMessage: "{{paymentMethod}} 已从你的账号中移除。",
          title: "移除付款方式",
        },
        actionLabel__default: "设为默认",
        actionLabel__remove: "移除",
        add: "添加新付款方式",
        addSubtitle: "为你的账号添加新的付款方式。",
        cancelButton: "取消",
        formButtonPrimary__add: "添加付款方式",
        formButtonPrimary__pay: "支付 {{amount}}",
        payWithTestCardButton: "使用测试卡付款",
        title: "付款方式",
      },
      start: {
        headerTitle__payments: "付款",
        headerTitle__plans: "方案",
        headerTitle__statements: "账单",
        headerTitle__subscriptions: "订阅",
      },
      statementsSection: {
        empty: "暂无可显示的账单",
        itemCaption__paidForPlan: "已支付 {{plan}} {{period}}方案",
        itemCaption__payerCredit: "从账号余额中抵扣",
        itemCaption__proratedCredit: "先前订阅部分使用时段的按比例抵扣额",
        itemCaption__subscribedAndPaidForPlan: "已订阅并支付 {{plan}} {{period}}方案",
        notFound: "未找到账单",
        tableHeader__amount: "金额",
        tableHeader__date: "日期",
        title: "账单",
        totalPaid: "已支付总额",
      },
      subscriptionsListSection: {
        actionLabel__manageSubscription: "管理",
        actionLabel__newSubscription: "订阅方案",
        actionLabel__switchPlan: "切换方案",
        includedSeatsUsage: "包含 {{includedSeats}} 个席位",
        overview: "概览",
        paidSeatsUsage: "{{seatsQuantity}} 个席位 × {{amount}}",
        seatLimit: "最多 {{seatLimit}} 个席位",
        seatLimitAndIncludedSeats: "最多 {{seatLimit}} 个席位（已包含 {{includedSeats}} 个）",
        tableHeader__edit: "编辑",
        tableHeader__plan: "方案",
        tableHeader__startDate: "开始日期",
        title: "订阅",
      },
      subscriptionsSection: {
        actionLabel__default: "管理",
      },
      switchPlansSection: {
        title: "切换方案",
      },
      title: "账单",
    },
    createDomainPage: {
      subtitle: "添加域名以进行验证。具有此域名电子邮件地址的用户可以自动加入组织或请求加入。",
      title: "添加域名",
    },
    invitePage: {
      detailsTitle__inviteFailed: "无法发送邀请。以下邮箱已有待处理邀请：{{email_addresses}}。",
      formButtonPrimary__continue: "发送邀请",
      selectDropdown__role: "选择角色",
      subtitle: "邀请新成员加入此组织",
      successMessage: "邀请成功发送",
      title: "邀请成员",
      formButtonPrimary__purchaseSeats: "购买额外席位",
    },
    membersPage: {
      action__invite: "邀请",
      activeMembersTab: {
        menuAction__remove: "移除成员",
        tableHeader__joined: "加入",
        tableHeader__role: "角色",
        tableHeader__user: "用户",
        tableHeader__actions: "操作",
      },
      alerts: {
        roleSetMigrationInProgress: {
          subtitle: "我们正在更新可用角色。完成后，您将能够再次更新角色。",
          title: "角色暂时被锁定",
        },
      },
      detailsTitle__emptyRow: "没有可显示的成员",
      invitationsTab: {
        autoInvitations: {
          headerSubtitle:
            "通过将电子邮件域名与您的组织连接来邀请用户。任何使用匹配电子邮件域名注册的人都可以随时加入组织。",
          headerTitle: "自动邀请",
          primaryButton: "管理已验证域名",
        },
        table__emptyRow: "没有可显示的邀请",
      },
      invitedMembersTab: {
        menuAction__revoke: "撤销邀请",
        tableHeader__invited: "已邀请",
      },
      requestsTab: {
        autoSuggestions: {
          headerSubtitle: "使用匹配电子邮件域名注册的用户将能够看到请求加入您组织的建议。",
          headerTitle: "自动建议",
          primaryButton: "管理已验证域名",
        },
        menuAction__approve: "批准",
        menuAction__reject: "拒绝",
        tableHeader__requested: "已请求访问",
        table__emptyRow: "没有可显示的请求",
      },
      start: {
        headerTitle__invitations: "邀请",
        headerTitle__members: "成员",
        headerTitle__requests: "请求",
      },
      action__search: "搜索",
    },
    navbar: {
      description: "管理您的组织。",
      general: "常规",
      members: "成员",
      title: "组织",
      apiKeys: "API 密钥",
      billing: "账单",
      security: "安全",
    },
    plansPage: {
      alerts: {
        noPermissionsToManageBilling: "你没有管理此组织账单的权限。",
        planMembershipLimitExceeded:
          "你的组织有 {{count}} 位成员（包括待接受的邀请）。此方案仅允许 {{limit}} 位成员。",
      },
      title: "方案",
    },
    profilePage: {
      dangerSection: {
        deleteOrganization: {
          actionDescription: '在下方输入 "{{organizationName}}" 以继续。',
          messageLine1: "您确定要删除此组织吗？",
          messageLine2: "此操作是永久性的且无法撤销。",
          successMessage: "您已删除该组织。",
          title: "删除组织",
        },
        leaveOrganization: {
          actionDescription: '在下方输入 "{{organizationName}}" 以继续。',
          messageLine1: "您确定要离开此组织吗？您将失去对此组织及其应用程序的访问权限。",
          messageLine2: "此操作是永久性的且无法撤销。",
          successMessage: "您已离开了组织。",
          title: "离开组织",
        },
        title: "危险",
      },
      domainSection: {
        menuAction__manage: "管理",
        menuAction__remove: "删除",
        menuAction__verify: "验证",
        primaryButton: "添加域名",
        subtitle: "允许用户根据已验证的电子邮件域名自动加入组织或请求加入。",
        title: "已验证域名",
      },
      successMessage: "组织信息已更新。",
      title: "组织简介",
    },
    removeDomainPage: {
      messageLine1: "电子邮件域名 {{domain}} 将被删除。",
      messageLine2: "此后，用户将无法自动加入组织。",
      successMessage: "{{domain}} 已被删除。",
      title: "删除域名",
    },
    securityPage: {
      connectionPage: {
        actions: {
          activate: "启用",
          continueSetup: "继续设置",
        },
        dangerZone: {
          deactivateButton: "停用连接",
          removeButton: "移除连接",
          title: "危险操作",
        },
        domains: {
          title: "域名",
        },
        identityProvider: {
          clientSecret: {
            placeholder: "留空以保留当前密钥",
          },
          form: {
            title: "编辑身份提供商",
          },
          certificateExpires: "证书到期时间",
          editButton: "编辑",
          title: "身份提供商",
        },
        name: {
          form: {
            title: "重命名连接",
          },
          editButton: "编辑",
          title: "名称",
        },
        serviceProvider: {
          acsUrl: "断言消费者服务（ACS）URL",
          entityId: "实体 ID",
          metadataUrl: "元数据 URL",
          redirectUri: "重定向 URI",
          title: "服务提供商",
        },
        settings: {
          allowAdditionalIdentifiers: {
            description: "成员可以保留其他登录方式。",
            label: "允许额外标识符",
          },
          allowIdpInitiated: {
            description: "可以从身份提供商发起登录。",
            label: "允许 IdP 发起的流程",
          },
          allowSubdomains: {
            description: "同时匹配连接域名的子域名。",
            label: "允许子域名",
          },
          forceAuthn: {
            description: "每次登录时，都在身份提供商处重新验证身份。",
            label: "强制重新验证身份",
          },
          syncUserAttributes: {
            description: "每次登录时，从身份提供商刷新姓名和电子邮箱。",
            label: "同步用户属性",
          },
          title: "设置",
        },
      },
      directorySyncSection: {
        removeDialog: {
          confirmButton: "移除目录同步",
          subtitle:
            "确定要移除目录同步吗？此操作无法撤销：目录及其 Bearer 令牌将被删除，身份提供商将无法再预配成员。现有成员将保留成员身份。",
          title: "移除目录同步",
        },
        badge__active: "已启用",
        badge__inactive: "未启用",
        badge__ssoRequired: "必须使用 SSO",
        badge__unconfigured: "未配置",
        description: "从身份提供商的目录自动添加、更新和移除组织成员。需要 SSO 连接。",
        error__load: "无法加载目录同步",
        menuAction__activate: "启用",
        menuAction__deactivate: "停用",
        menuAction__edit: "编辑",
        menuAction__remove: "移除",
        primaryButton__startConfiguration: "开始配置",
        title: "目录同步",
      },
      removeDialog: {
        confirmButton: "移除连接",
        subtitle: "确定要移除连接“{{name}}”吗？此操作无法撤销，将删除连接及其全部配置。",
        title: "移除 SSO 连接",
      },
      ssoBypassPage: {
        addForm: {
          emailPlaceholder: "输入成员的电子邮箱地址",
          error__allAlreadyAdded: "拥有此角色的所有人都已在允许列表中。",
          error__alreadyAdded: "此成员已在允许列表中。",
          error__memberNotFound: "此组织中没有成员使用该电子邮箱地址。",
          modeLabel: "添加依据",
          mode__email: "电子邮箱",
          mode__role: "角色",
          roleOption: "{{role}}（{{count}}）",
          roleWarning: "此列表不会同步，成员需手动管理。",
          submitButton: "添加成员",
          subtitle: "SSO 不可用时，此列表中的成员可以使用电子邮箱验证码登录。",
          title: "添加成员",
        },
        bulkResult: {
          added: "已添加 {{count}} 位成员",
          addedMember: "已成功添加成员",
          added__one: "已添加 1 位成员",
          domainNotServed: "无法添加 {{count}} 位成员，因为没有连接支持其电子邮箱地址。",
          domainNotServed__one: "无法添加 1 位成员，因为没有连接支持其电子邮箱地址。",
          notMember: "无法添加 {{count}} 位成员，因为他们已不在此组织中。",
          notMember__one: "无法添加 1 位成员，因为该成员已不在此组织中。",
          unknown: "无法添加 {{count}} 位成员。",
          unknown__one: "无法添加 1 位成员。",
        },
        table: {
          emptyState: "允许列表中没有成员",
          emptyState__search: "没有匹配搜索条件的成员",
          header__actions: "操作",
          header__user: "用户",
          menuAction__remove: "移除",
        },
        action__add: "添加",
        action__search: "搜索用户",
        title: "绕过 SSO",
      },
      ssoBypassSection: {
        allowlistCount: "{{count}} 位成员",
        allowlistCount__one: "1 位成员",
        allowlistLabel: "允许列表：",
        description: "SSO 不可用时，此列表中的成员可以使用电子邮箱验证码登录。",
        error__load: "无法加载 SSO 允许列表",
        menuAction__manage: "管理",
        title: "绕过 SSO",
      },
      ssoSection: {
        badge__active: "已启用",
        badge__inProgress: "进行中",
        badge__inactive: "未启用",
        badge__unconfigured: "未配置",
        descriptionLine1: "要求电子邮箱域名匹配的成员通过你的身份提供商登录。",
        domainLabel: "域名：",
        menuAction__activate: "启用",
        menuAction__continue: "继续配置",
        menuAction__deactivate: "停用",
        menuAction__edit: "编辑",
        menuAction__remove: "移除",
        primaryButton__addConnection: "添加连接",
        primaryButton__continueConfiguration: "继续配置",
        primaryButton__startConfiguration: "开始配置",
        title: "SSO",
        tooltip:
          "电子邮箱域名不匹配的成员仍可使用现有验证方式登录。新成员将在此组织中被分配为 {{role}}。",
        tooltipLabel: "更多信息",
        tooltip__noRole: "电子邮箱域名不匹配的成员仍可使用现有验证方式登录。",
      },
      title: "安全",
    },
    start: {
      headerTitle__general: "常规",
      headerTitle__members: "成员",
      profileSection: {
        primaryButton: "更新组织简介",
        title: "组织简介",
        uploadAction__title: "标志",
      },
      membershipSeatUsageLabel: "已使用 {{count}} 个席位，共 {{limit}} 个",
    },
    verifiedDomainPage: {
      dangerTab: {
        calloutInfoLabel: "删除此域名将影响受邀用户。",
        removeDomainActionLabel__remove: "删除域名",
        removeDomainSubtitle: "从您的已验证域名中删除此域名",
        removeDomainTitle: "删除域名",
      },
      enrollmentTab: {
        automaticInvitationOption__description:
          "用户在注册时会自动收到加入组织的邀请，并且可以随时加入。",
        automaticInvitationOption__label: "自动邀请",
        automaticSuggestionOption__description:
          "用户会收到请求加入的建议，但在加入组织之前必须得到管理员的批准。",
        automaticSuggestionOption__label: "自动建议",
        calloutInfoLabel: "更改注册模式只会影响新用户。",
        calloutInvitationCountLabel: "已发送给用户的待处理邀请：{{count}}",
        calloutSuggestionCountLabel: "已发送给用户的待处理建议：{{count}}",
        manualInvitationOption__description: "用户只能被手动邀请加入组织。",
        manualInvitationOption__label: "无自动注册",
        subtitle: "选择此域名的用户如何加入组织。",
      },
      start: {
        headerTitle__danger: "危险",
        headerTitle__enrollment: "注册选项",
      },
      subtitle: "域名 {{domain}} 现已验证。继续选择注册模式。",
      title: "更新 {{domain}}",
    },
    verifyDomainPage: {
      formSubtitle: "输入发送到您邮箱地址的验证码",
      formTitle: "验证码",
      resendButton: "未收到验证码？重新发送",
      subtitle: "域名 {{domainName}} 需要通过电子邮件进行验证。",
      subtitleVerificationCodeScreen: "验证码已发送到 {{emailAddress}}。输入验证码以继续。",
      title: "验证域名",
    },
    badge__enterpriseSso: "企业 SSO",
  },
  organizationSwitcher: {
    action__createOrganization: "创建组织",
    action__invitationAccept: "加入",
    action__manageOrganization: "管理组织",
    action__suggestionsAccept: "请求加入",
    notSelected: "未选择组织",
    personalWorkspace: "个人工作区",
    suggestionsAcceptedLabel: "等待批准",
    action__closeOrganizationSwitcher: "关闭组织切换器",
    action__openOrganizationSwitcher: "打开组织切换器",
  },
  paginationButton__next: "下一页",
  paginationButton__previous: "上一页",
  paginationRowText__displaying: "显示",
  paginationRowText__of: "的",
  reverification: {
    alternativeMethods: {
      getHelp: {
        blockButton__emailSupport: "通过电子邮件联系支持团队",
        content: "如果你在验证账号时遇到问题，请给我们发送电子邮件，我们会协助你尽快恢复访问。",
        title: "获取帮助",
      },
      actionLink: "获取帮助",
      actionText: "这些方式都无法使用？",
      blockButton__backupCode: "使用备用验证码",
      blockButton__emailCode: "向 {{identifier}} 发送电子邮箱验证码",
      blockButton__passkey: "使用通行密钥",
      blockButton__password: "使用密码继续",
      blockButton__phoneCode: "向 {{identifier}} 发送 SMS 验证码",
      blockButton__totp: "使用身份验证器应用",
      subtitle: "遇到问题？你可以使用以下任一方式验证身份。",
      title: "使用其他方式",
    },
    backupCodeMfa: {
      subtitle: "输入设置双重验证时获得的备用验证码",
      title: "输入备用验证码",
    },
    emailCode: {
      formTitle: "验证码",
      resendButton: "未收到验证码？重新发送",
      subtitle: "输入发送到电子邮箱的验证码以继续",
      title: "需要验证",
    },
    noAvailableMethods: {
      message: "无法继续验证，尚未配置合适的身份验证因素",
      subtitle: "发生错误",
      title: "无法验证你的账号",
    },
    passkey: {
      blockButton__passkey: "使用通行密钥",
      subtitle: "使用通行密钥可以确认你的身份。设备可能会要求你提供指纹、人脸或锁屏验证。",
      title: "使用通行密钥",
    },
    password: {
      actionLink: "使用其他方式",
      subtitle: "输入当前密码以继续",
      title: "需要验证",
    },
    phoneCode: {
      formTitle: "验证码",
      resendButton: "未收到验证码？重新发送",
      subtitle: "输入发送到手机的验证码以继续",
      title: "需要验证",
    },
    phoneCodeMfa: {
      formTitle: "验证码",
      resendButton: "未收到验证码？重新发送",
      subtitle: "输入发送到手机的验证码以继续",
      title: "需要验证",
    },
    totpMfa: {
      formTitle: "验证码",
      subtitle: "输入身份验证器应用生成的验证码以继续",
      title: "需要验证",
    },
  },
  searchInput: {
    action__clear: "清除搜索",
  },
  signIn: {
    accountSwitcher: {
      action__addAccount: "添加账户",
      action__signOutAll: "退出所有账户",
      subtitle: "选择您要继续使用的账户。",
      title: "选择一个账户",
    },
    alternativeMethods: {
      actionLink: "获取帮助",
      actionText: "没有这些？",
      blockButton__backupCode: "使用备用代码",
      blockButton__emailCode: "电子邮件验证码到 {{identifier}}",
      blockButton__emailLink: "电子邮件链接到 {{identifier}}",
      blockButton__password: "使用您的密码登录",
      blockButton__phoneCode: "发送短信代码到 {{identifier}}",
      blockButton__totp: "使用您的验证应用程序",
      getHelp: {
        blockButton__emailSupport: "邮件支持",
        content: "如果您在登录账户时遇到困难，请给我们发送电子邮件，我们将尽快让您恢复访问。",
        title: "获取帮助",
      },
      subtitle: "遇到问题？您可以使用以下任何方法登录。",
      title: "使用其他方法",
      blockButton__passkey: "使用通行密钥登录",
    },
    alternativePhoneCodeProvider: {
      formTitle: "验证码",
      resendButton: "未收到验证码？重新发送",
      subtitle: "以继续使用 {{applicationName}}",
      title: "查看你的 {{provider}}",
    },
    backupCodeMfa: {
      subtitle: "备份验证码是在设置双重验证时获得的。",
      title: "输入备用代码",
    },
    emailCode: {
      formTitle: "验证码",
      resendButton: "重新发送验证码",
      subtitle: "继续使用 {{applicationName}}",
      title: "查看您的电子邮件",
    },
    emailCodeMfa: {
      formTitle: "查看您的电子邮件",
      resendButton: "未收到验证码？重新发送",
      subtitle: "继续使用 {{applicationName}}",
      title: "查看您的电子邮件",
    },
    emailLink: {
      clientMismatch: {
        subtitle: "要继续，请在发起登录的设备和浏览器中打开验证链接",
        title: "验证链接不适用于此设备",
      },
      expired: {
        subtitle: "返回原始标签页继续。",
        title: "此验证链接已过期",
      },
      failed: {
        subtitle: "返回原始标签页继续。",
        title: "此验证链接无效",
      },
      formSubtitle: "使用发送到您的电子邮件的验证链接",
      formTitle: "验证链接",
      loading: {
        subtitle: "即将为您重定向",
        title: "正在登录...",
      },
      resendButton: "重新发送链接",
      subtitle: "继续使用 {{applicationName}}",
      title: "查看您的电子邮件",
      unusedTab: {
        title: "您可以关闭此标签页",
      },
      verified: {
        subtitle: "即将为您重定向",
        title: "成功登录",
      },
      verifiedSwitchTab: {
        subtitle: "返回原始标签页继续",
        subtitleNewTab: "返回新打开的标签页继续",
        titleNewTab: "在其他标签页上登录",
      },
      verifiedTransferable: {
        subtitle: "返回原标签页以继续",
        title: "电子邮箱已验证",
      },
    },
    emailLinkMfa: {
      formSubtitle: "使用发送到您电子邮件的验证链接",
      resendButton: "没有收到链接？重新发送",
      subtitle: "继续使用 {{applicationName}}",
      title: "查看您的电子邮件",
    },
    enterpriseConnections: {
      subtitle: "选择企业账号以继续。",
      title: "选择账号",
    },
    enterpriseSSO: {
      formButtonPrimary: "使用 SSO 继续",
    },
    forgotPassword: {
      formTitle: "重置密码代码",
      resendButton: "重新发送代码",
      subtitle: "以重置您的密码",
      subtitle_email: "首先，输入发送到您的电子邮件 ID 的代码",
      subtitle_phone: "首先，输入发送到您手机的代码",
      title: "重置密码",
    },
    forgotPasswordAlternativeMethods: {
      blockButton__resetPassword: "重置密码",
      label__alternativeMethods: "或者，使用其他方式登录。",
      title: "忘记密码？",
    },
    newDeviceVerificationNotice: "您正在从新设备登录。我们需要验证以保护您的账户安全。",
    noAvailableMethods: {
      message: "无法继续登录。没有可用的身份验证因素。",
      subtitle: "出现错误",
      title: "无法登录",
    },
    passkey: {
      subtitle: "使用通行密钥可以确认是你本人。设备可能会要求你提供指纹、人脸或锁屏验证。",
      title: "使用通行密钥",
    },
    password: {
      actionLink: "使用其他方法",
      subtitle: "输入账号密码",
      title: "输入您的密码",
    },
    passwordCompromised: {
      title: "密码已泄露",
    },
    passwordPwned: {
      title: "密码已泄露",
    },
    passwordUntrusted: {
      title: "密码不受信任",
    },
    phoneCode: {
      formTitle: "验证码",
      resendButton: "重新发送验证码",
      subtitle: "继续使用 {{applicationName}}",
      title: "检查手机短信",
    },
    phoneCodeMfa: {
      formTitle: "验证码",
      resendButton: "重新发送验证码",
      subtitle: "请继续输入发送到您手机的验证码。",
      title: "检查手机短信",
    },
    protectCheck: {
      loading: "正在加载…",
      retryButton: "重试",
      subtitle: "请稍候，我们正在验证你的请求。",
      title: "正在验证你的请求",
    },
    resetPassword: {
      formButtonPrimary: "重置密码",
      requiredMessage: "出于安全原因，需要重置您的密码。",
      successMessage: "您的密码已成功更改。正在为您登录，请稍等。",
      title: "重置密码",
    },
    resetPasswordMfa: {
      detailsLabel: "我们需要验证您的身份才能重置您的密码。",
    },
    ssoBypass: {
      code: {
        resendButton: "未收到验证码？重新发送",
        subtitle: "以继续使用 {{applicationName}}",
        title: "查看电子邮箱",
      },
      actionLink: "无法使用 SSO？",
      notice: "你的组织要求使用单点登录。不使用单点登录继续操作将被记录。",
    },
    start: {
      actionLink: "注册",
      actionLink__use_email: "使用电子邮件",
      actionLink__use_email_username: "使用电子邮件或用户名",
      actionLink__use_phone: "使用电话",
      actionLink__use_username: "使用用户名",
      actionText: "还没有账户？",
      alternativePhoneCodeProvider: {
        actionLink: "使用其他方式",
        label: "{{provider}} 电话号码",
        subtitle: "输入电话号码，以通过 {{provider}} 获取验证码。",
        title: "使用 {{provider}} 登录 {{applicationName}}",
      },
      subtitle: "欢迎回来！请登录您的账户以继续。",
      title: "登录 {{applicationName}}",
      titleCombined: "继续使用 {{applicationName}}",
      actionLink__join_waitlist: "加入等候名单",
      actionLink__use_passkey: "改用通行密钥",
      actionText__join_waitlist: "想要抢先体验？",
    },
    totpMfa: {
      formTitle: "验证码",
      subtitle: "请继续输入由您的身份验证应用生成的验证码。",
      title: "两步验证",
    },
    web3Solana: {
      subtitle: "请选择下方的钱包进行登录",
      title: "使用 Solana 登录",
    },
  },
  signInEnterPasswordTitle: "输入您的密码",
  signUp: {
    alternativePhoneCodeProvider: {
      resendButton: "未收到验证码？重新发送",
      subtitle: "输入发送到 {{provider}} 的验证码",
      title: "验证你的 {{provider}}",
    },
    continue: {
      actionLink: "登录",
      actionText: "已经有账户了？",
      subtitle: "请补全其余信息以继续。",
      title: "填写缺少的字段",
    },
    emailCode: {
      formSubtitle: "输入发送到您的电子邮件地址的验证码",
      formTitle: "验证码",
      resendButton: "重新发送验证码",
      subtitle: "输入发送到邮箱的验证码",
      title: "验证您的电子邮件",
    },
    emailLink: {
      clientMismatch: {
        subtitle: "要继续，请在发起注册的设备和浏览器中打开验证链接",
        title: "验证链接不适用于此设备",
      },
      formSubtitle: "使用发送到您的电子邮件地址的验证链接",
      formTitle: "验证链接",
      loading: {
        title: "正在注册...",
      },
      resendButton: "重新发送链接",
      subtitle: "继续使用 {{applicationName}}",
      title: "验证您的电子邮件",
      verified: {
        title: "成功注册",
      },
      verifiedSwitchTab: {
        subtitle: "返回新打开的标签页继续",
        subtitleNewTab: "返回上一个标签页继续",
        title: "成功验证电子邮件",
      },
    },
    enterpriseConnections: {
      subtitle: "选择企业账号以继续。",
      title: "选择账号",
    },
    legalConsent: {
      checkbox: {
        label__onlyPrivacyPolicy: '我同意 {{ privacyPolicyLink || link("Privacy Policy") }}',
        label__onlyTermsOfService: '我同意 {{ termsOfServiceLink || link("Terms of Service") }}',
        label__termsOfServiceAndPrivacyPolicy:
          '我同意 {{ termsOfServiceLink || link("Terms of Service") }} 和 {{ privacyPolicyLink || link("Privacy Policy") }}',
      },
      continue: {
        subtitle: "请阅读并接受条款以继续",
        title: "法律条款同意",
      },
    },
    phoneCode: {
      formSubtitle: "输入发送到您的电话号码的验证码",
      formTitle: "验证码",
      resendButton: "重新发送验证码",
      subtitle: "输入发送到手机的验证码",
      title: "验证您的电话",
    },
    protectCheck: {
      loading: "正在加载…",
      retryButton: "重试",
      subtitle: "请稍候，我们正在验证你的请求。",
      title: "正在验证你的请求",
    },
    restrictedAccess: {
      actionLink: "登录",
      actionText: "已有账号？",
      blockButton__emailSupport: "通过电子邮件联系支持团队",
      blockButton__joinWaitlist: "加入等候名单",
      subtitle: "目前已关闭注册。如果你认为自己应拥有访问权限，请联系支持团队。",
      subtitleWaitlist: "目前已关闭注册。加入等候名单，即可在开放时率先收到通知。",
      title: "访问受限",
    },
    start: {
      actionLink: "登录",
      actionText: "已经有账户了？",
      alternativePhoneCodeProvider: {
        actionLink: "使用其他方式",
        label: "{{provider}} 电话号码",
        subtitle: "输入电话号码，以通过 {{provider}} 获取验证码。",
        title: "使用 {{provider}} 注册 {{applicationName}}",
      },
      subtitle: "请填写信息以开始。",
      subtitleCombined: "请填写信息以开始。",
      title: "创建您的账户",
      titleCombined: "创建您的账户",
      actionLink__use_email: "改用电子邮箱",
      actionLink__use_phone: "改用手机",
    },
    web3Solana: {
      subtitle: "请选择下方的钱包进行注册",
      title: "使用 Solana 注册",
    },
  },
  socialButtonsBlockButton: "使用 {{provider|titleize}} 登录",
  taskChooseOrganization: {
    alerts: {
      organizationAlreadyExists:
        "检测到的公司名称 ({{organizationName}}) 和 {{organizationDomain}} 已存在一个组织。请通过邀请加入。",
    },
    chooseOrganization: {
      action__createOrganization: "创建新组织",
      action__invitationAccept: "加入",
      action__suggestionsAccept: "请求加入",
      subtitle: "加入现有组织或创建新组织",
      subtitle__createOrganizationDisabled: "加入现有组织",
      suggestionsAcceptedLabel: "等待批准",
      title: "选择组织",
    },
    createOrganization: {
      formButtonReset: "取消",
      formButtonSubmit: "继续",
      formFieldInputPlaceholder__name: "我的组织",
      formFieldInputPlaceholder__slug: "wo-de-zu-zhi",
      formFieldLabel__name: "名称",
      formFieldLabel__slug: "Slug",
      subtitle: "输入您的组织详细信息以继续",
      title: "设置您的组织",
    },
    organizationCreationDisabled: {
      subtitle: "请联系您的组织管理员获取邀请。",
      title: "您必须属于一个组织",
    },
    signOut: {
      actionLink: "退出",
      actionText: "已登录为 {{identifier}}",
    },
  },
  taskResetPassword: {
    signOut: {
      actionLink: "退出登录",
      actionText: "登录账号：{{identifier}}",
    },
    formButtonPrimary: "重置密码",
    subtitle: "你的账号需要设置新密码后才能继续",
    title: "重置密码",
  },
  taskSetupMfa: {
    signOut: {
      actionLink: "退出登录",
      actionText: "登录账号：{{identifier}}",
    },
    smsCode: {
      addPhone: {
        formButtonPrimary: "继续",
        infoText: "我们会向此电话号码发送含验证码的短信，可能产生短信和数据费用。",
      },
      success: {
        finishButton: "继续",
        message1: "双重验证已启用。登录时，你还需要输入发送到此电话号码的验证码。",
        message2:
          "请保存这些备用验证码，并妥善保管。如果无法使用身份验证设备，你可以通过备用验证码登录。",
        title: "SMS 验证码验证已启用",
      },
      verifyPhone: {
        formButtonPrimary: "继续",
        formTitle: "验证码",
        resendButton: "未收到验证码？重新发送",
        subtitle: "输入验证码，验证码已发送至",
        title: "验证电话号码",
      },
      addPhoneNumber: "添加电话号码",
      cancel: "取消",
      subtitle: "选择用于 SMS 验证码双重验证的电话号码",
      title: "添加 SMS 验证码验证",
    },
    start: {
      methodSelection: {
        phoneCode: "SMS 验证码",
        totp: "身份验证器应用",
      },
      subtitle: "选择你偏好的方式，为账号增加一层安全保护",
      title: "设置双重验证",
    },
    totpCode: {
      addAuthenticatorApp: {
        buttonAbleToScan__nonPrimary: "改为扫描二维码",
        buttonUnableToScan__nonPrimary: "无法扫描二维码？",
        formButtonPrimary: "继续",
        formButtonReset: "取消",
        infoText__ableToScan:
          "在身份验证器应用中设置新的登录方式，扫描以下二维码，将其关联到你的账号。",
        infoText__unableToScan: "在身份验证器中设置新的登录方式，并输入下方提供的密钥。",
        inputLabel__unableToScan1: "确保已启用基于时间的密码或一次性密码，然后完成账号关联。",
      },
      success: {
        finishButton: "继续",
        message1: "双重验证已启用。登录时，你还需要输入此身份验证器生成的验证码。",
        message2:
          "请保存这些备用验证码，并妥善保管。如果无法使用身份验证设备，你可以通过备用验证码登录。",
        title: "身份验证器应用验证已启用",
      },
      verifyTotp: {
        formButtonPrimary: "继续",
        formButtonReset: "取消",
        formTitle: "验证码",
        subtitle: "输入身份验证器生成的验证码",
        title: "添加身份验证器应用",
      },
      title: "添加身份验证器应用",
    },
    badge: "双重验证设置",
  },
  unstable__errors: {
    avatar_file_size_exceeded: "文件大小超过10MB的最大限制。请选择一个较小的文件。",
    avatar_file_type_invalid: "不支持的文件类型。请上传 JPG、PNG、GIF 或 WEBP 格式的图片。",
    captcha_invalid: "由于安全验证失败，注册未成功。请刷新页面重试或联系支持获取更多帮助。",
    captcha_unavailable:
      "注册失败，原因是未通过机器人验证。请刷新页面重试或联系支持团队以获取更多帮助。",
    form_email_address_blocked: "不支持临时电子邮件服务。请使用您的常规电子邮件地址创建账户。",
    form_identifier_not_found: "我们无法找到具有这些信息的账户。",
    form_param_format_invalid__email_address: "邮箱地址必须是有效的邮箱格式。",
    form_param_format_invalid__phone_number: "电话号码必须符合有效的国际格式。",
    form_param_max_length_exceeded__first_name: "名字长度不得超过256个字符。",
    form_param_max_length_exceeded__last_name: "姓氏长度不得超过256个字符。",
    form_param_max_length_exceeded__name: "姓名长度不得超过256个字符。",
    form_password_not_strong_enough: "您的密码强度不够。",
    form_password_or_identifier_incorrect: "密码或电子邮件地址不正确。请重试或使用其他方法。",
    form_password_pwned: "这个密码在数据泄露中被发现，不能使用，请换一个密码试试。",
    form_password_size_in_bytes_exceeded:
      "您的密码超过了允许的最大字节数，请缩短它或去掉一些特殊字符。",
    form_password_validation_failed: "密码错误",
    form_username_needs_non_number_char: "您的用户名必须包含至少一个非数字字符。",
    identification_deletion_failed: "您无法删除最后一个身份标识。",
    not_allowed_access:
      "您使用的电子邮件地址或电话号码不允许注册。这可能是因为您在电子邮件地址中使用了 '+', '=', '#' 或 '.'，使用了与临时电子邮件服务关联的域名，或者有明确的排除。如果您认为这是错误，请联系支持。",
    passwordComplexity: {
      maximumLength: "少于{{length}}个字符",
      minimumLength: "{{length}}个或更多字符",
      requireLowercase: "一个小写字母",
      requireNumbers: "一个数字",
      requireSpecialCharacter: "一个特殊字符",
      requireUppercase: "一个大写字母",
      sentencePrefix: "您的密码必须包含",
    },
    phone_number_exists: "该电话号码已被使用，请尝试其他号码。",
    session_exists: "您已登录。",
    web3_signature_request_rejected: "您已拒绝签名请求。请重试以继续。",
    web3_solana_signature_generation_failed: "生成签名时发生错误。请重试以继续。",
    zxcvbn: {
      couldBeStronger: "您的密码可以用，但可以更强。试着添加更多字符。",
      goodPassword: "做得好。这是一个优秀的密码。",
      notEnough: "您的密码强度不够。",
      suggestions: {
        allUppercase: "大写一些，但不是所有的字母。",
        anotherWord: "添加更不常见的更多单词。",
        associatedYears: "避免与你有关的年份。",
        capitalization: "大写不仅仅是第一个字母。",
        dates: "避免与你有关的日期和年份。",
        l33t: '避免预测的字母替换，如"@"代替"a"。',
        longerKeyboardPattern: "使用更长的键盘模式，并多次改变打字方向。",
        noNeed: "你可以创建强密码，而无需使用符号，数字或大写字母。",
        pwned: "如果您在其他地方使用此密码，您应该更改它。",
        recentYears: "避免近年来。",
        repeated: "避免重复的单词和字符。",
        reverseWords: "避免常用词的反向拼写。",
        sequences: "避免常见字符序列。",
        useWords: "使用多个单词，但避免常见短语。",
      },
      warnings: {
        common: "这是一个常用的密码。",
        commonNames: "常见的名字和姓氏易被猜到。",
        dates: "日期易被猜到。",
        extendedRepeat: '像"abcabcabc"这样的重复字符模式易被猜到。',
        keyPattern: "短键盘模式易被猜到。",
        namesByThemselves: "单个名字或姓氏易被猜到。",
        pwned: "您的密码在互联网上的数据泄露中被暴露。",
        recentYears: "近年来易被猜到。",
        sequences: '像"abc"这样的常见字符序列易被猜到。',
        similarToCommon: "这个密码和常用密码相似。",
        simpleRepeat: '像"aaa"这样的重复字符易被猜到。',
        straightRow: "键盘上的直行键易被猜到。",
        topHundred: "这是一个频繁使用的密码。",
        topTen: "这是一个大量使用的密码。",
        userInputs: "不应该有任何个人或页面相关的数据。",
        wordByItself: "单个单词易被猜到。",
      },
    },
    action_blocked: "无法完成此操作。请稍后重试；如果问题持续，请联系支持团队。",
    already_a_member_in_organization: "{{email}} 已是此组织的成员。",
    api_key_name_already_exists: "API 密钥名称已存在。",
    api_key_usage_exceeded: "你已达到用量上限。升级到付费方案即可解除限制。",
    form_new_password_matches_current: "新密码不能与当前密码相同。",
    form_password_length_too_short: "密码过短，至少需要 8 个字符。",
    form_password_matches_identifier:
      "密码不能与电子邮箱地址、电话号码或用户名相同。为了账号安全，请使用其他密码。",
    form_password_pwned__sign_in: "此密码已出现在泄露数据中，无法使用。请重置密码。",
    form_password_untrusted__sign_in:
      "你的密码可能已泄露。为了保护账号，请使用其他登录方式继续。登录后，你需要重置密码。",
    form_username_invalid_length: "用户名长度必须在 {{min_length}} 至 {{max_length}} 个字符之间。",
    insufficient_seats_change_plan:
      "组织的席位不足，无法邀请所需数量的成员。请切换到支持该成员数量的方案。",
    insufficient_seats_contact_support: "组织的席位不足，无法邀请所需数量的成员。请联系支持团队。",
    oauth_access_denied: "你未授予账号访问权限。",
    organization_membership_quota_exceeded: "你加入的组织数量已达上限，包括尚未接受的邀请。",
    organization_not_found_or_unauthorized: "你已不再是此组织的成员。请选择或创建其他组织。",
    organization_not_found_or_unauthorized_with_create_organization_disabled:
      "你已不再是此组织的成员。请选择其他组织。",
    passkey_already_exists: "此设备已注册通行密钥。",
    passkey_not_supported: "此设备不支持通行密钥。",
    passkey_pa_not_supported: "注册需要平台身份验证器，但此设备不支持。",
    passkey_registration_cancelled: "通行密钥注册已取消或超时。",
    passkey_retrieval_cancelled: "通行密钥验证已取消或超时。",
    protect_check_execution_failed: "验证未完成，请重试。",
    protect_check_invalid_script: "无法加载验证。如果问题持续，请联系支持团队。",
    protect_check_invalid_sdk_url: "无法开始验证。请联系支持团队。",
    protect_check_required:
      "此次登录需要额外的验证步骤，但无法在此显示。请重试或使用其他登录方式。",
    protect_check_script_load_failed:
      "无法加载验证。可能是网络问题，或内容安全策略（Content Security Policy）阻止了验证脚本。请重试或联系支持团队。",
    protect_check_timed_out: "验证未在规定时间内完成，请重试。",
    protect_check_unsupported_environment:
      "此环境不支持验证。请在标准浏览器中继续，或联系支持团队。",
    sso_bypass_domain_not_served: "无法添加此成员，因为没有连接支持其电子邮箱地址。",
    ticket_expired_code: "此链接已过期。请重新开始或请求新链接。",
    ticket_invalid_code: "此链接已失效或已使用。请重新开始或请求新链接。",
    web3_missing_identifier: "未找到 Web3 钱包扩展。请安装后再继续。",
  },
  userButton: {
    action__addAccount: "添加账户",
    action__closeUserMenu: "关闭用户菜单",
    action__manageAccount: "管理账户",
    action__openUserMenu: "打开用户菜单",
    action__signOut: "退出登录",
    action__signOutAll: "退出所有账户",
    label__accountActions: "账户操作",
    label__activeSessions: "活跃会话",
    label__userButtonPopover: "账户面板",
  },
  userProfile: {
    apiKeysPage: {
      title: "API 密钥",
    },
    backupCodePage: {
      actionLabel__copied: "已复制！",
      actionLabel__copy: "复制全部",
      actionLabel__download: "下载 .txt",
      actionLabel__print: "打印",
      infoText1: "将为此账户启用备份代码。",
      infoText2: "保密并安全存储备份代码。如果您怀疑它们已经泄露，您可以重新生成备份代码。",
      subtitle__codelist: "安全存储并保守秘密。",
      successMessage:
        "现在已启用备份代码。如果您失去了验证设备的访问权限，您可以使用其中之一登录您的账户。每个代码只能使用一次。",
      successSubtitle: "如果您失去了验证设备的访问权限，您可以使用其中之一登录您的账户。",
      title: "添加备份代码验证",
      title__codelist: "备份代码",
    },
    billingPage: {
      accountCreditsSection: {
        title: "账号余额",
        viewHistory: "查看余额记录",
      },
      creditHistoryPage: {
        tableHeader__amount: "金额",
        tableHeader__date: "日期",
        title: "账号余额记录",
      },
      paymentHistorySection: {
        empty: "暂无付款记录",
        notFound: "未找到付款尝试",
        tableHeader__amount: "金额",
        tableHeader__date: "日期",
        tableHeader__status: "状态",
      },
      paymentMethodsSection: {
        removeMethod: {
          messageLine1: "{{identifier}} 将从此账号中移除。",
          messageLine2: "你将无法再使用此付款来源，依赖它的定期订阅也将停止正常续费。",
          successMessage: "{{paymentMethod}} 已从你的账号中移除。",
          title: "移除付款方式",
        },
        actionLabel__default: "设为默认",
        actionLabel__remove: "移除",
        add: "添加新付款方式",
        addSubtitle: "为你的账号添加新的付款方式。",
        cancelButton: "取消",
        formButtonPrimary__add: "添加付款方式",
        formButtonPrimary__pay: "支付 {{amount}}",
        payWithTestCardButton: "使用测试卡付款",
        title: "付款方式",
      },
      start: {
        headerTitle__payments: "付款",
        headerTitle__plans: "方案",
        headerTitle__statements: "账单",
        headerTitle__subscriptions: "订阅",
      },
      statementsSection: {
        empty: "暂无可显示的账单",
        itemCaption__paidForPlan: "已支付 {{plan}} {{period}}方案",
        itemCaption__payerCredit: "从账号余额中抵扣",
        itemCaption__proratedCredit: "先前订阅部分使用时段的按比例抵扣额",
        itemCaption__subscribedAndPaidForPlan: "已订阅并支付 {{plan}} {{period}}方案",
        notFound: "未找到账单",
        tableHeader__amount: "金额",
        tableHeader__date: "日期",
        title: "账单",
        totalPaid: "已支付总额",
      },
      subscriptionsListSection: {
        actionLabel__manageSubscription: "管理",
        actionLabel__newSubscription: "订阅方案",
        actionLabel__switchPlan: "切换方案",
        overview: "概览",
        tableHeader__edit: "编辑",
        tableHeader__plan: "方案",
        tableHeader__startDate: "开始日期",
        title: "订阅",
      },
      subscriptionsSection: {
        actionLabel__default: "管理",
      },
      switchPlansSection: {
        title: "切换方案",
      },
      title: "账单",
    },
    connectedAccountPage: {
      formHint: "选择一个供应商来连接您的账户。",
      formHint__noAccounts: "没有可用的外部账户供应商。",
      removeResource: {
        messageLine1: "{{identifier}} 将从此账户中被移除。",
        messageLine2: "您将无法再使用这个已连接的账户，任何依赖的功能将不再工作。",
        successMessage: "{{connectedAccount}} 已从您的账户中移除。",
        title: "移除已连接的账户",
      },
      socialButtonsBlockButton: "连接 {{provider|titleize}} 账户",
      successMessage: "供应商已被添加到您的账户",
      title: "添加已连接的账户",
    },
    deletePage: {
      actionDescription: '在下方输入 "删除账户" 以继续。',
      confirm: "删除账户",
      messageLine1:
        "您确定要删除您的账户吗？某些关联数据可能会被保留。要请求完全删除数据，请联系支持团队。",
      messageLine2: "此操作是永久且不可逆的。",
      title: "删除账户",
    },
    emailAddressPage: {
      emailCode: {
        formHint: "一封含有验证码的邮件将会被发送到这个电子邮件地址。",
        formSubtitle: "输入发送到 {{identifier}} 的验证码",
        formTitle: "验证码",
        resendButton: "重发验证码",
        successMessage: "电子邮件 {{identifier}} 已被添加到您的账户。",
      },
      emailLink: {
        formHint: "一封含有验证链接的邮件将会被发送到这个电子邮件地址。",
        formSubtitle: "点击发送到 {{identifier}} 的邮件中的验证链接",
        formTitle: "验证链接",
        resendButton: "重发链接",
        successMessage: "电子邮件 {{identifier}} 已被添加到您的账户。",
      },
      enterpriseSSOLink: {
        formButton: "点击登录",
        formSubtitle: "使用 {{identifier}} 完成登录",
      },
      formHint: "这个电子邮件地址必须在验证之后才能被添加到您的账户。",
      removeResource: {
        messageLine1: "{{identifier}} 将从此账户中被移除。",
        messageLine2: "您将无法使用这个电子邮件地址登录。",
        successMessage: "电子邮件 {{emailAddress}} 已从您的账户中移除。",
        title: "移除电子邮件地址",
      },
      title: "添加电子邮件地址",
      verifyTitle: "验证电子邮件地址",
    },
    formButtonPrimary__add: "添加",
    formButtonPrimary__continue: "继续",
    formButtonPrimary__finish: "完成",
    formButtonPrimary__remove: "移除",
    formButtonPrimary__save: "保存",
    formButtonReset: "取消",
    mfaPage: {
      formHint: "选择一个添加的方法。",
      title: "添加两步验证",
    },
    mfaPhoneCodePage: {
      backButton: "使用现有号码",
      primaryButton__addPhoneNumber: "添加电话号码",
      removeResource: {
        messageLine1: "{{identifier}} 将不再在登录时接收验证代码。",
        messageLine2: "您的账户可能不再安全。您确定要继续吗？",
        successMessage: "已移除{{mfaPhoneCode}}的短信验证码两步验证",
        title: "移除两步验证",
      },
      subtitle__availablePhoneNumbers: "选择一个电话号码来注册短信验证码两步验证。",
      subtitle__unavailablePhoneNumbers: "没有可用的电话号码来注册短信验证码两步验证。",
      successMessage1: "登录时，您需要输入发送到此电话号码的验证码作为额外的步骤。",
      successMessage2:
        "请保存这些备份代码并将其妥善存放。如果您无法访问身份验证设备，可以使用备份代码进行登录。",
      successTitle: "短信验证码验证已启用",
      title: "添加短信验证码验证",
    },
    mfaTOTPPage: {
      authenticatorApp: {
        buttonAbleToScan__nonPrimary: "扫描二维码",
        buttonUnableToScan__nonPrimary: "不能扫描二维码？",
        infoText__ableToScan:
          "在您的验证器应用中设置一个新的登录方法，并扫描下面的二维码将其链接到您的账户。",
        infoText__unableToScan: "在验证器中设置一个新的登录方法，并输入下面提供的 Key。",
        inputLabel__unableToScan1: "确保启用了基于时间或一次性密码，然后完成链接您的账户。",
        inputLabel__unableToScan2: "或者，如果您的验证器支持 TOTP URIs，您也可以复制完整的 URI。",
      },
      removeResource: {
        messageLine1: "登录时，将不再需要来自此验证器的验证码。",
        messageLine2: "您的账户可能不再安全。您确定要继续吗？",
        successMessage: "已移除通过验证器应用程序的两步验证。",
        title: "移除两步验证",
      },
      successMessage: "现在已启用两步验证。在登录时，您需要输入来自此验证器的验证码作为额外步骤。",
      title: "添加验证器应用程序",
      verifySubtitle: "输入您的验证器生成的验证码",
      verifyTitle: "验证代码",
    },
    mobileButton__menu: "菜单",
    navbar: {
      account: "账户",
      description: "管理您的账户。",
      security: "安全",
      title: "账户",
      apiKeys: "API 密钥",
      billing: "账单",
    },
    passkeyScreen: {
      removeResource: {
        messageLine1: "{{name}} 将从此账号中移除。",
        title: "移除通行密钥",
      },
      subtitle__rename: "你可以修改通行密钥名称，以便查找。",
      title__rename: "重命名通行密钥",
    },
    passwordPage: {
      checkboxInfoText__signOutOfOtherSessions:
        "建议您从所有可能使用过旧密码的其他设备上退出登录。",
      readonly: "由于您只能通过企业连接登录，当前无法编辑您的密码。",
      successMessage__set: "您的密码已设置。",
      successMessage__signOutOfOtherSessions: "所有其他设备已退出。",
      successMessage__update: "您的密码已更新。",
      title__set: "设置密码",
      title__update: "更改密码",
    },
    phoneNumberPage: {
      infoText: "一条包含验证链接的短信将会发送到这个电话号码。",
      removeResource: {
        messageLine1: "{{identifier}} 将从此账户中被移除。",
        messageLine2: "您将无法使用这个电话号码登录。",
        successMessage: "电话号码 {{phoneNumber}} 已从您的账户中移除。",
        title: "移除电话号码",
      },
      successMessage: "{{identifier}} 已被添加到您的账户。",
      title: "添加电话号码",
      verifySubtitle: "请输入发送至 {{identifier}} 的验证码",
      verifyTitle: "验证电话号码",
    },
    plansPage: {
      title: "方案",
    },
    profilePage: {
      fileDropAreaHint: "上传小于10MB的JPG, PNG, GIF, 或WEBP格式的图片",
      imageFormDestructiveActionSubtitle: "移除图片",
      imageFormSubtitle: "上传图片",
      imageFormTitle: "个人资料图片",
      readonly: "您的个人信息由企业连接提供，无法进行编辑。",
      successMessage: "您的个人资料已更新。",
      title: "更新个人资料",
    },
    start: {
      activeDevicesSection: {
        destructiveAction: "退出设备",
        title: "活动设备",
      },
      connectedAccountsSection: {
        actionLabel__connectionFailed: "再试一次",
        actionLabel__reauthorize: "立即授权",
        destructiveActionTitle: "移除",
        primaryButton: "连接账户",
        subtitle__reauthorize:
          "“所需的权限范围已更新，您可能会遇到功能受限的问题。请重新授权此应用程序，以避免出现任何问题。”",
        title: "已连接的账户",
        subtitle__disconnected: "此账号已断开连接。",
      },
      dangerSection: {
        deleteAccountButton: "删除账户",
        title: "终止账户",
      },
      emailAddressesSection: {
        destructiveAction: "移除电子邮件地址",
        detailsAction__nonPrimary: "设为主要",
        detailsAction__primary: "完成验证",
        detailsAction__unverified: "完成验证",
        primaryButton: "添加电子邮件地址",
        title: "电子邮件地址",
      },
      enterpriseAccountsSection: {
        primaryButton: "连接账户",
        title: "企业账户",
      },
      headerTitle__account: "账户",
      headerTitle__security: "安全",
      mfaSection: {
        backupCodes: {
          actionLabel__regenerate: "重新生成代码",
          headerTitle: "备份代码",
          subtitle__regenerate: "获取一套新的安全备份代码。之前的备份代码将被删除，无法使用。",
          title__regenerate: "重新生成备份代码",
        },
        phoneCode: {
          actionLabel__setDefault: "设为默认",
          destructiveActionLabel: "移除电话号码",
        },
        primaryButton: "添加两步验证",
        title: "两步验证",
        totp: {
          destructiveActionTitle: "移除",
          headerTitle: "验证器应用程序",
        },
      },
      passkeysSection: {
        menuAction__destructive: "移除",
        menuAction__rename: "重命名",
        primaryButton: "添加通行密钥",
        title: "通行密钥",
      },
      passwordSection: {
        primaryButton__setPassword: "设置密码",
        primaryButton__updatePassword: "更改密码",
        title: "密码",
      },
      phoneNumbersSection: {
        destructiveAction: "移除电话号码",
        detailsAction__nonPrimary: "设为主要",
        detailsAction__primary: "完成验证",
        detailsAction__unverified: "完成验证",
        primaryButton: "添加电话号码",
        title: "电话号码",
      },
      profileSection: {
        primaryButton: "更新个人资料",
        title: "个人资料",
      },
      usernameSection: {
        primaryButton__setUsername: "设置用户名",
        primaryButton__updateUsername: "更改用户名",
        title: "用户名",
      },
      web3WalletsSection: {
        destructiveAction: "移除钱包",
        primaryButton: "Web3 钱包",
        title: "Web3 钱包",
        web3SelectSolanaWalletScreen: {
          subtitle: "选择一个 Solana 钱包以连接到您的账户。",
          title: "添加 Solana 钱包",
        },
        detailsAction__nonPrimary: "设为主要",
      },
    },
    usernamePage: {
      successMessage: "您的用户名已更新。",
      title__set: "更新用户名",
      title__update: "更新用户名",
    },
    web3WalletPage: {
      removeResource: {
        messageLine1: "{{identifier}} 将从此账户中被移除。",
        messageLine2: "您将无法使用这个 web3 钱包登录。",
        successMessage: "{{web3Wallet}} 已从您的账户中移除。",
        title: "移除 web3 钱包",
      },
      subtitle__availableWallets: "选择一个 web3 钱包连接到您的账户。",
      subtitle__unavailableWallets: "没有可用的 web3 钱包。",
      successMessage: "钱包已被添加到您的账户。",
      title: "添加web3钱包",
      web3WalletButtonsBlockButton: "{{provider|titleize}}",
    },
  },
  waitlist: {
    start: {
      actionLink: "登录",
      actionText: "已有访问权限？",
      formButton: "加入候补名单",
      subtitle: "输入您的电子邮件地址，我们会在您的位置准备好时通知您",
      title: "加入候补名单",
    },
    success: {
      message: "您将很快被重定向...",
      subtitle: "当您的位置准备好时，我们会与您联系",
      title: "感谢您加入候补名单！",
    },
  },
  web3SolanaWalletButtons: {
    connect: "使用 {{walletName}} 连接",
    continue: "使用 {{walletName}} 继续",
    noneAvailable:
      '未检测到 Solana Web3 钱包。请安装支持 Web3 的 {{ solanaWalletsLink || link("wallet extension") }}。',
  },
  badge__activePlan: "生效中",
  badge__banned: "已封禁",
  badge__canceledEndsAt: "已取消 • 于 {{ date | shortDate('en-US') }} 结束",
  badge__currentPlan: "当前方案",
  badge__deprovisioned: "已解除预配",
  badge__endsAt: "于 {{ date | shortDate('en-US') }} 结束",
  badge__expired: "已过期",
  badge__freeTrial: "免费试用",
  badge__pastDueAt: "于 {{ date | shortDate('en-US') }} 逾期",
  badge__pastDuePlan: "已逾期",
  badge__renewsAt: "于 {{ date | shortDate('en-US') }} 续订",
  badge__startsAt: "于 {{ date | shortDate('en-US') }} 开始",
  badge__trialEndsAt: "试用于 {{ date | shortDate('en-US') }} 结束",
  badge__upcomingPlan: "即将生效",
  footerActionLink__alternativePhoneCodeProvider: "改为通过 SMS 发送验证码",
  formFieldInputPlaceholder__apiKeyDescription: "说明生成此密钥的原因",
  formFieldInputPlaceholder__apiKeyExpirationDate: "选择日期",
  formFieldInputPlaceholder__apiKeyName: "输入私密密钥名称",
  formFieldInputPlaceholder__backupCode: "输入备用验证码",
  formFieldInputPlaceholder__emailAddress_username: "输入电子邮箱或用户名",
  formFieldInputPlaceholder__firstName: "名",
  formFieldInputPlaceholder__lastName: "姓",
  formFieldInputPlaceholder__organizationDomain: "example.com",
  formFieldInputPlaceholder__organizationDomainEmailAddress: "you@example.com",
  formFieldInputPlaceholder__organizationName: "组织名称",
  formFieldInputPlaceholder__password: "输入密码",
  formFieldInputPlaceholder__phoneNumber: "输入电话号码",
  formFieldInputPlaceholder__signUpPassword: "创建密码",
  formFieldInputPlaceholder__username: "输入用户名",
  formFieldInput__emailAddress_format: "格式示例：name@example.com",
  formFieldLabel__passkeyName: "通行密钥名称",
  identityPreviewEditButton__emailAddress: "编辑电子邮箱地址",
  identityPreviewEditButton__identifier: "编辑标识符",
  identityPreviewEditButton__phoneNumber: "编辑电话号码",
  maintenanceMode: "我们目前正在维护，预计只需几分钟。",
  socialButtonsBlockButtonManyInView: "{{provider|titleize}}",
} as const;
