// swift-tools-version:6.1
// Harmony port of T3 Code's iOS native modules.
//
// The upstream Swift sources are vendored verbatim (except for a deterministic
// `import UIKit` -> `import T3UIKit` rewrite performed by tools/sync-upstream.mjs)
// and compiled against pure-Swift shim modules that reproduce the exact Apple API
// surface those sources use. Everything builds and tests on any Swift host; the
// OpenHarmony cross-build links the same sources against the OHOS sysroot.
import PackageDescription

let package = Package(
  name: "T3SwiftCore",
  platforms: [.macOS(.v13)],
  products: [
    // static：设备侧把它整体链接进 libt3bridge.so（NAPI 边界）。
    .library(name: "T3SwiftCore", type: .static, targets: ["T3SwiftCore"])
  ],
  targets: [
    // Geometry + retained drawing: a recording CGContext that emits a Codable
    // display list, replayed 1:1 by the ArkUI canvas renderer on device.
    .target(name: "T3CoreGraphics", path: "swift/Sources/T3CoreGraphics"),
    .target(name: "T3QuartzCore", dependencies: ["T3CoreGraphics"], path: "swift/Sources/T3QuartzCore"),
    .target(name: "T3UIKit", dependencies: ["T3CoreGraphics", "T3QuartzCore"], path: "swift/Sources/T3UIKit"),
    // Recording implementation of the Expo modules DSL: the vendored module
    // definitions become a declarative registry the bridge introspects, so the
    // prop/event/async-function surface travels with the upstream source.
    .target(name: "T3ExpoModulesCore", dependencies: ["T3UIKit"], path: "swift/Sources/T3ExpoModulesCore"),
    // GhosttyKit surface API. On the host it is backed by an injectable
    // terminal engine; on OpenHarmony the engine is libghostty-vt.
    .target(name: "T3GhosttyKit", dependencies: ["T3CoreGraphics"], path: "swift/Sources/T3GhosttyKit"),
    // iOS-only presentation frameworks, distilled to the recording surface the
    // vendored control module drives; playback/preview are fulfilled by the
    // embedder (ArkUI native components) through presentation records.
    .target(name: "T3AVKit", dependencies: ["T3UIKit"], path: "swift/Sources/T3AVKit"),
    .target(name: "T3QuickLook", dependencies: ["T3UIKit"], path: "swift/Sources/T3QuickLook"),
    .target(name: "T3ImageIO", dependencies: ["T3CoreGraphics"], path: "swift/Sources/T3ImageIO"),
    .target(name: "T3UniformTypeIdentifiers", path: "swift/Sources/T3UniformTypeIdentifiers"),
    // Vendored upstream modules (generated by tools/sync-upstream.mjs).
    .target(name: "VendoredT3ReviewDiff", dependencies: ["T3ExpoModulesCore"], path: "vendor/swift/t3-review-diff"),
    .target(
      name: "VendoredT3ComposerEditor", dependencies: ["T3ExpoModulesCore"], path: "vendor/swift/t3-composer-editor"),
    .target(name: "VendoredT3Terminal", dependencies: ["T3ExpoModulesCore", "T3GhosttyKit"], path: "vendor/swift/t3-terminal"),
    .target(
      name: "VendoredT3NativeControls",
      dependencies: ["T3ExpoModulesCore", "T3AVKit", "T3QuickLook", "T3ImageIO", "T3UniformTypeIdentifiers"],
      path: "vendor/swift/t3-native-controls"),
    // Generic bridge: view registry, prop/event/async-function dispatch, display
    // list export, text-measurement protocol, scroll/gesture/tick drivers.
    .target(
      name: "T3Bridge",
      dependencies: [
        "T3CoreGraphics", "T3QuartzCore", "T3UIKit", "T3ExpoModulesCore", "T3GhosttyKit",
        "VendoredT3ReviewDiff", "VendoredT3ComposerEditor", "VendoredT3Terminal", "VendoredT3NativeControls",
      ],
      path: "swift/Sources/T3Bridge"),
    .target(name: "T3SwiftCore", dependencies: ["T3Bridge"], path: "swift/Sources/T3SwiftCore"),
    // C ABI over the bridge: the seam the NAPI layer links against.
    .target(
      name: "T3CABI",
      dependencies: ["T3Bridge", "T3CoreGraphics", "T3ExpoModulesCore", "T3SwiftCore"],
      path: "swift/Sources/T3CABI"),
    // XCTest is unavailable on a CommandLineTools-only host; the test runner is
    // a zero-dependency executable that exits nonzero on the first failure.
    .executableTarget(
      name: "T3TestRunner",
      dependencies: ["T3SwiftCore"],
      path: "swift/Tests/T3TestRunner"),
    // 诊断工具：dump 一帧 display list JSON（ArkTS 回放器的对照真值）。
    .executableTarget(
      name: "T3Dump",
      dependencies: ["T3SwiftCore"],
      path: "swift/Tests/T3Dump"),
  ],
  swiftLanguageVersions: [.v5]
)
